### ISSUE TITLE
Generate nicer SQL for "is NULL"

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#101]
The 

```perl6
use Red;

model Foo {
    has Int $.bar is serial;
    has Str $.foo is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Foo.^create-table;

say Foo.^all.grep(not *.foo.defined );

```

Gives

```sql
SELECT
   foo.foo , foo.bar 
FROM
   foo
WHERE
   NOT (foo IS NOT NULL)
```

Which is perfectly valid SQL but, well, not very pretty and possibly doesn't play nicely with the query optimizers of some engines.

Would it be possible to have a ```prefix:<not>``` specialised to Red::AST::IsDefined which somehow toggles the ```NOT``` in the ```IS NOT NULL```?

The same technique could probably be used for ```NOT BETWEEN``` and ```NOT IN``` among others.

**Comment by FCO** [comment]
I think it would be easier to create an optimizer for that...

**Comment by jonathanstowe** [comment]
On a related note using ```!``` instead of ```not``` there leads to 

```
Cannot resolve caller where(Foo::ResultSeq:D: Bool:D); none of these signatures match:
    (Foo::ResultSeq:U: Red::AST:U $filter, *%_)
    (Foo::ResultSeq:D: Red::AST:U $filter, *%_)
    (Foo::ResultSeq:U: Red::AST:D $filter, *%_)
    (Foo::ResultSeq:D: Red::AST:D $filter, *%_)
  in method grep at /home/jns/.rakudobrew/moar-master/install/share/perl6/site/sources/692BB37FCBC7D93EDAA86CC860BCC78F1F0096D1 (Red::ResultSeq) line 67
  in block <unit> at tt line 13
```

Which is just the want of a ```multi prefix:<!> ( Red::AST:U $filter)```` or some such.

**Comment by jonathanstowe** [comment]
Just on a train at the moment but the commits look good.  I'll take a better look when I get home 👍

**Comment by jonathanstowe** [comment]
Checked the above code with both ```not``` and ```!``` and all good.

Good to close.

Top Work! :+1:
