### ISSUE TITLE
Possible Documentation Error

### ISSUE THREAD

**Issue by Michael-S** [FCO/Red#107]
More likely this is user error, I hope I'm not wasting your time.  In the README it has:
say Person.new(:2id)
    .active-posts
    .grep: { .created > Date.today }  
\# SELECT * FROM post me WHERE;                                     
\# me.author_id = ? **AND me.deleted = 't'**
\# AND me.created > '2018-08-14'::datetime
\# with [2] as bind.
**(Emphasis mine)**

I do not understand how that part of the SQL query is created from the code above.  Is it a mistake?

**Comment by FCO** [comment]
You are right, that's wrong! I've fixed it... it should be `AND me.deleted = 'f'`.
It's that way, because `active-posts` is defined as `method active-posts { @!posts.grep: { not .deleted } }`

Thank you!
