### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by federico-razzoli** [FCO/Red#109]
It would be nice to have default values for columns - which means, defined using the DEFAULT clause in SQL.

**Comment by FCO** [comment]
That would be good to use the default value of the model, but also have a way to say to not using that as default.

```perl6
model Bla {
   has Int $.a is column = 42;
   has Int $.b is column{ :ignore-default } = 13; # or any other name
}
```

```sql
create table bla(
   a integer not null default 42,
   b integer not null
)
```

**Comment by FCO** [comment]
```perl6fe
model Bla {
   has Int $.a is column = 42;
   has Int $.b is column{ :ignore-default } = 13; # or any other name
   has Int $.c is-column{ :default(3) };
}
```


```sql
create table bla(
   a integer not null default 42,
   b integer not null,
   c integer not null default 3
)
```

**Comment by jonathanstowe** [comment]
Also it would be useful to be able to supply literal SQL as the default.

```sql
create table bla(
    foo uuid primary key default uuid_generate_v4() 
);
```

In say Postgres.

I'm not quite sure how one might express that in the model declaration though.

**Comment by FCO** [comment]
Maybe something like:

```perl6
has UUID $.foo is column{ :default(“uiid_generate_v4()”) };
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanstowe** [comment]
Except you'd need to distinguish between a string default and verbatim SQL.

**Comment by FCO** [comment]
`:default-sql(“uuid_henerate_v4()”)`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
I've been wondering...
If I do this:

```perl6
model Bla { has $.ble is column{ :default-sql<NOW()> } }

Bla.new
```

should the `new` run a `SELECT NOW()` on database to populate the object?

**Comment by FCO** [comment]
I mean:

```perl6
model Bla {
    has Instante $.bla is column{ :default-sql<NOW()> };
    has Int          $.ble is column;
    has UUID      $.bli is column .= new;
    has UUID.     $.blo is column{ :default-sql<uuid_henerate_v4()> }
}

Bla.new
```

would

```sql
SELECT NOW() as bla, uuid_henerate_v4() as blo
```

**Comment by santec** [comment]
I could be wrong, but I think you won't be able to handle cases where a default value references another column - or at least, not in all databases. Example, this may not work on some DBMSs:

`SELECT 2000 AS price, price + (price / 100) * 20 AS taxed_price`

**Comment by FCO** [comment]
Maybe something like this:

```perl6
model Bla {
    has Instante $.bla is column{ :default{ .now } };
    has Int       $.ble is column;
    has UUID      $.bli is column .= new;
    has UUID      $.blo is column{ :default{ .new-v4 } }
    has Int       $.blu is column{ :42default };
}
```

**Comment by jonathanstowe** [comment]
I'd like to be able to describe a table like:

```sql
CREATE TABLE bla (
    uuid uuid DEFAULT public.uuid_generate_v4()  PRIMARY KEY,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL
);
```

So the ```default-sql``` should become part of the DDL for the table.  The advantage of being able to do it like this is so that non-Red applications will get the same behaviour.

**Comment by FCO** [comment]
Yes, in my suggestion, to create that table, you could use something like:

```perl6
model Bla {
    has UUID     $.uuid is id{ :default{ .generate-v4() } };
    has Instant $.created-at is column{ :default{ .now() } }
}
```

and a column of time UUID would have the `generate-v4` method that returns a AST that creates the `public.uuid_generate_v4()` call, and the same for created-at...

what do you think?

**Comment by FCO** [comment]
if we do like `:default-sql<public.uuid_generate_v4()>` it will only work on databases that has that function with that name...

**Comment by jonathanstowe** [comment]
Got ya!  Yep I like that.

**Comment by FCO** [comment]
@jonathanstowe just to be sure, you mean this one, right? https://github.com/FCO/Red/issues/109#issuecomment-472923770

**Comment by jonathanstowe** [comment]
Yep.  And just so we're clear we mean the same thing, I understand that the driver would proved a translate method to create the SQL to define a default of that type.

**Comment by FCO** [comment]
Tha’s it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/99834/182006232-8e8768b3-2bc3-41f9-b1e8-c151303b44da.png">
