### ISSUE TITLE
Add a comment to easily find the query in the code

### ISSUE THREAD

**Issue by santec** [FCO/Red#113]
It would be nice to insert a comment in the queries, that help to find the query in the code. I don't know if this is possible in PERL6 but, ideally, it would be nice to have information like:

- File name
- Line number
- Function name

**Comment by FCO** [comment]
```
$ perl6 -e '


sub where { say do given callframe(2) {%(line => .line, file => .file, code => .code.name) } }
sub bla {
   where;
   where;
   where;
}
bla

' 
{code => bla, file => -e, line => 6}
{code => bla, file => -e, line => 7}
{code => bla, file => -e, line => 8}
```

**Comment by jonathanstowe** [comment]
A possible complication is that a query may be built up over many lines of code and not _materialized_ until later when say ```.all``` is called, so you'd want to think about where you'd want it report as I'm not sure the ```translate``` method that finally creates the SQL would be that useful.  Perhaps the ```callframe``` could be attached to the AST objects if debugging is turned on.

**Comment by FCO** [comment]
Yes... maybe the info on the ast and add the comment with every line/file that contributed to create that query...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
with this commit (c09e08e3219f925d26f24d9e5bcf41bb84768cf3), now it is possible:

```
$ perl6 -Ilib -MRed -e '


model Bla { has Int $.a is column }

my $*RED-DB = database "SQLite"; 
my $*RED-DEBUG = True;

Bla.^create-table;
my $*RED-COMMENT-SQL = True;
sub bla {
   Bla.^all.grep(*.a == 2).map: *.a
}

say bla

'
SQL : CREATE TABLE bla(
   a  integer  NOT NULL       
)
BIND: []
SQL : -- method 'grep' called at:
-- file : -e
-- block: bla
-- line : 12

-- method 'map' called at:
-- file : -e
-- block: bla
-- line : 12

SELECT
   bla.a as "data_1"
FROM
   bla
WHERE
   bla.a = 2
BIND: []
()
```

**Comment by FCO** [comment]
Please, any comment? @jonathanstowe @santec 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanstowe** [comment]
Nice.  It might be worth considering  another variable (or even repurposing this one,) such that if it is a routine with one argument and returns a Str will be called with the callframe to generate the text of the comment.

But yeah it will be really useful to know where a surprising query came from when trying to debug stuff.

**Comment by FCO** [comment]
That makes sense! Good idea!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
```
$ perl6 -Ilib -MRed -e '


model Bla { has Int $.a is column }

my $*RED-DB = database "SQLite"; 
my $*RED-DEBUG = True;

Bla.^create-table;
my $*RED-COMMENT-SQL = True;
sub bla {
   Bla.^all.grep(*.a == 2).map: *.a
}
                                                                                                   
say bla

'
SQL : CREATE TABLE bla(
   a  integer  NOT NULL       
)
BIND: []
SQL : -- method 'grep' called at: -e #12

-- method 'map' called at: -e #12

SELECT
   bla.a as "data_1"
FROM
   bla
WHERE
   bla.a = 2
BIND: []
()
$ perl6 -Ilib -MRed -e '


model Bla { has Int $.a is column }

my $*RED-DB = database "SQLite"; 
my $*RED-DEBUG = True;

Bla.^create-table;
                            
sub bla {
   Bla.^all.grep(*.a == 2).map: *.a
}
my &*RED-COMMENT-SQL = -> :$meth-name, :$file, :$block, | { "$meth-name called on $file: $block" }
say bla

'
SQL : CREATE TABLE bla(
   a  integer  NOT NULL       
)
BIND: []
SQL : -- grep called on -e: bla

-- map called on -e: bla

SELECT
   bla.a as "data_1"
FROM
   bla
WHERE
   bla.a = 2
BIND: []
()
```

**Comment by jonathanstowe** [comment]
Hi,
On reflection it may want to do something extra with the callframes for the SQL generated for relations as currently the comments point to the ```build-relationship``` method:

```
SQL : -- method 'head' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block:
-- line : 53

-- method 'do-it' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block: head
-- line : 53

-- method 'Seq' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block: do-it
-- line : 53

SELECT
   tinky_state.id , tinky_state.name , tinky_state.workflow_id as "workflow-id"
FROM
   tinky_state
WHERE
   tinky_state.id = ?
BIND: [1]
SQL : -- method 'head' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block:
-- line : 53

-- method 'do-it' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block: head
-- line : 53

-- method 'Seq' called at:
-- file : /home/jonathan/devel/perl6/3rdparty-modules/Red/lib/Red/Attr/Relationship.pm6 (Red::Attr::Relationship)
-- block: do-it
-- line : 53

SELECT
   tinky_workflow.name , tinky_workflow.initial_state_id as "initial-state-id", tinky_workflow.id 
FROM
   tinky_workflow
WHERE
   tinky_workflow.id = ?
BIND: [1]

```

**Comment by FCO** [comment]
@jonathanstowe would you mind to see if it fixed the problem please?

**Comment by jonathanstowe** [comment]
Well in this case it seems exactly the same, if you look at this test with the https://github.com/jonathanstowe/Tinky-DB/blob/master/t/100-synopsis.t#L83 uncommented it seems to run the query to get ```inititial-state``` over and over again, but I can't see where it can be called from as it shouldn't even be accessing that at that point.

**Comment by jonathanstowe** [comment]
The actual thing that is going on there is a separate issue, I just can't get enough diagnostic information to reason about it.

**Comment by FCO** [comment]
@jonathanstowe Would you mind to try it again?

**Comment by jonathanstowe** [comment]
Well, it's definitely different and in this particular case somewhat helpful, so now I now something genuinely weird is going on:

```
SQL : -- method 'head' called at: SETTING::src/core/Mu.pm6 #606

-- method 'do-it' called at: SETTING::src/core/Mu.pm6 #606

-- method 'Seq' called at: SETTING::src/core/Mu.pm6 #606

SELECT
   tinky_workflow.name , tinky_workflow.id , tinky_workflow.initial_state_id as "initial-state-id"
FROM
   tinky_workflow
WHERE
   tinky_workflow.id = ?
BIND: [1]
SQL : -- method 'head' called at: SETTING::src/core/Mu.pm6 #636

-- method 'do-it' called at: SETTING::src/core/Mu.pm6 #636

-- method 'Seq' called at: SETTING::src/core/Mu.pm6 #636

SELECT
   tinky_workflow.name , tinky_workflow.id , tinky_workflow.initial_state_id as "initial-state-id"
FROM
   tinky_workflow
WHERE
   tinky_workflow.id = ?
BIND: [1]
```

Which basically points to  ```Mu.perl``` which is a bit strange.  But yes, that works.  I think the problem is with what ```is-deeply``` does for some reason.

**Comment by FCO** [comment]
Thanks! Ill try to take a look on it tonight...

**Comment by jonathanstowe** [comment]
It's somewhat specific to the code but could be a common trap.  I'm going to put a separate ticket in.
