### ISSUE TITLE
Support MySQL storage engines

### ISSUE THREAD

**Issue by federico-razzoli** [FCO/Red#114]
It would be nice to support creation of a table with a certain storage engine. By default, I also suggest we make sure that

-- for example, if i try to use RocksDB and it's not installed, by default I'd like to get an error
SET SESSION sql_mode := CONCAT(@@sql_mode, ',NO_ENGINE_SUBSTITUTION');

I suggest that we define a default storage engine in the ORM, which is not necessarily the same defined in MySQL. If so, it would be even better having 2: one for regular tables, one for temporary tables.

It would also be nice to have a function to check if an engine is installed (SHOW ENGINES).

**Comment by jonathanstowe** [comment]
It would probably be worth considering the various other DBMS specific storage features such as Pg (or Oracle) tablespaces and possibly attached databases for SQLite.  I think I've mentioned the latter in another ticket regarding namespaces.

**Comment by FCO** [comment]
it should, probably, have a way to pass parameters to the model and let it be used/tested by the driver.
