### ISSUE TITLE
Support NULL-safe comparisons

### ISSUE THREAD

**Issue by federico-razzoli** [FCO/Red#116]
Support NULL-safe versions of = and !=

**MySQL / MariaDB**

- a <=> b
- NOT (a <=> b)

**PostgreSQL**

- a IS NOT DISTINCT FROM b
- a IS DISTINCT FROM b

**SQLite**

- a IS b
- a IS NOT b

**Comment by FCO** [comment]
It will be done when we have a MySQL driver.
