### ISSUE TITLE
Provide for no-op table creation if table exists

### ISSUE THREAD

**Issue by tbrowder** [FCO/Red#123]
Need equivalent of sql "create table if not exists tabname ..." [more correct syntax per @santec]

Currently "create-table" throws if the table exists. Either make default to be a silent no-op or have an adverb to request that option.

**Comment by jonathanstowe** [comment]
I'd go with an adverb or something as it might be a surprise that the table exists (like you specified the wrong database for instance.)

**Comment by FCO** [comment]
could it be a:

```perl6
multi method create-table(\model, Bool :$if-exists where so *) {
   try callwith model
}
```

?

**Comment by santec** [comment]
Some DBMSs have this syntax:

CREATE TABLE IF NOT EXISTS tab ( ... ) ;

Probably **NOT** using it and implementing it in the ORM would improve compatibility. Because there are some subtle details that are very dependent from the specific technology.
