### ISSUE TITLE
Feature request: method or sub to pretty-print an ASCII version of ResultSeq to $*OUT

### ISSUE THREAD

**Issue by tbrowder** [FCO/Red#136]
As can be done in RDBMS progs like SQLite:

    $ sqlite3 mydb.sqlite
    sqlite>
    sqlite> .tables
    attend email person present
    sqlite> 
    sqlite> .mode column
    sqlite>
    sqlite> select * from present;
    2012        3
    2010        100

But improved to show column titles, row sort options, etc., resulting in the table above looking
something like this:

    +------+-----+
    | year | id  |
    +------+-----+
    | 2010 | 100 |
    | 2012 |   3 |
    +------+-----+

 Note PostgreSQL may have a better ASCII display than SQLite.

**Comment by jonathanstowe** [comment]
A nice way to achieve this would be to allow for the provision of a formatter class to a ResultSeq (with some sensible default,)  the formattter class  would be consuming a role like : 

```perl6
   role ResultSeqFormatter {
        method format(Red::ResultSeq:D $rs ) {
        ...
       }
   }
```

So all instance would provide the ```format```  as appropriate  and this formatter object would then be used to format the ResultSeq for ```.Str``` or ```.gist```.   

We'd want to provide a number of different ways of specifying the formatter according to need.  E.g. by defining an explicit ResultSeq class:

```perl6

class Foo::ResultSeq is Red::ResultSeq {
     has Red::ResultSeq::Fomatter $.formatter = MyFormatter.new;
}
```

Or at run-time (for example):

```perl6
    say Foo.^rs.with-formatter(MyFormatter.new)
```

Or even globally with with a dynamic variable:

```perl6
    my  $*RED-RS-FORMATTER = MyFormatter.new;
```

There are probably other places where it might be convenient to set the formatter (on the Model class for instance,)

The advantage of this kind of scheme is that we don't need to provide multiple methods for different types of output and that no-one is stuck with an output type that isn't really useful to them.  I'd say there is probably a case for providing this for Model objects as well.

I'll have a fiddle to see if can make one that would provide the output you want later.

**Comment by jonathanstowe** [comment]
Your formatter would be something like:

```perl6
use Red;
  
model Foo {
    has Int $.id is serial;
    has Str $.foo is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Foo.^create-table;

Foo.^create(foo => "one");
Foo.^create(foo => "two");

sub formatter(Red::ResultSeq:D $rs --> Str ) {
    my @cols   = $rs.of.^attributes.grep(Red::Attr::Column).map( -> $c { $c.name.substr(2) });

    my $str = @cols.join("\t\t|");
    $str ~= "\n" ~ ( '-' x 50 ) ~ "\n";
    for $rs -> $row {
        $str ~= @cols.map( -> $n { $row."$n"() }).join("\t\t|") ~ "\n";
    }

   $str;
}
say formatter(Foo.^rs);
```

I cheated and used tabs rather than working out what width the columns should be.

**Comment by tbrowder** [comment]
Looking good--thanks!

**Comment by jonathanstowe** [comment]
To do the column widths properly it would be find the max length of the values and column name for each column and then do something like build a sprintf format for the row data.

**Comment by FCO** [comment]
I like the:

```my  $*RED-RS-FORMATTER = MyFormatter.new;```

Maybe it could be created also:

```
my  $*RED-RS-FORMATTER = Red::Formatter::AsciiTable.new;
my  $*RED-RS-FORMATTER = Red::Formatter::JSON.new;
my  $*RED-RS-FORMATTER = Red::Formatter::YAML.new;
my  $*RED-RS-FORMATTER = Red::Formatter::HTML.new;
my  $*RED-RS-FORMATTER = Red::Formatter::MD.new;
```

etc

**Comment by jonathanstowe** [comment]
Absolutely, but it's encourage people to make their own ;-)

**Comment by santec** [comment]
It would be nice to also have the vertical view:

```
***************************[ 1. row ]***************************
TABLE_CATALOG   | def
TABLE_SCHEMA    | information_schema
TABLE_NAME      | TABLES
TABLE_TYPE      | SYSTEM VIEW
ENGINE          | MEMORY
VERSION         | 10
ROW_FORMAT      | Fixed
TABLE_ROWS      | <null>
AVG_ROW_LENGTH  | 9441
DATA_LENGTH     | 0
MAX_DATA_LENGTH | 16757775
INDEX_LENGTH    | 0
DATA_FREE       | 0
AUTO_INCREMENT  | <null>
CREATE_TIME     | 2019-03-18 15:10:13
UPDATE_TIME     | <null>
CHECK_TIME      | <null>
TABLE_COLLATION | utf8_general_ci
CHECKSUM        | <null>
CREATE_OPTIONS  | max_rows=1777
TABLE_COMMENT   |
```

**Comment by jonathanstowe** [comment]
That's the point of allowing users to write their own :-)

**Comment by jonathanstowe** [comment]
JSON is easy BTW:

```perl6
use JSON::Class;
use Red;

model Foo {
    has Int $.id is serial;
    has Str $.foo is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Foo.^create-table;

Foo.^create(foo => "one");
Foo.^create(foo => "two");

sub formatter-json(Red::ResultSeq:D $rs --> Str) {
    ($rs but JSON::Class).to-json
}

say formatter-json(Foo.^rs);

```

Which is nice.

**Comment by FCO** [comment]
Now you can do something like this:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/99834/168704440-a899bec1-c0f0-47b9-b9fe-fe177032d65f.png">

And you can also implement the `Red::Formatter::ResultSeq` role and set `$*RED-FORMATTER-RESULTSEQ` to it to have it used when calling `.format` (or pass it as a single argument to `.format`) (it uses `Red::Formatter::ResultSeq::Vertical` as default)
