### ISSUE TITLE
Symbol for "between" operator?

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#139]
The SQL ```BETWEEN``` will be quite easy to implement now as #138 put in place the "list on the RHS" part.  But for the life of me I can't think of a good symbol to use (of course we could just use ```between``` but where's the fun in that?).

Alternatively I guess (and it might be cool to support this as well anyway,)  we could make a candidate for  'ge' which has a specific  ```Red::AST::Infix::Ge``` for the left argument so we can do:

```perl6
   1 <= *.bar <= 3
```
Which would generate the 'BETWEEN'

**Comment by FCO** [comment]
```
$ perl6 -e '
sub infix:<< £ >>(Int $a; Int $b; Int $c) is assoc<list> { "$b is between $a, $c" }; say 1 £ 2 £ 3;
sub infix:<< < >>(Int $a; Int $b; Int $c) is assoc<list> { "$b is between $a, $c" }; say 1 < 2 < 3;
'
2 is between 1, 3
Too few positionals passed; expected 3 arguments but got 2
  in sub infix:«<» at -e line 3
  in block <unit> at -e line 3
```

**Comment by FCO** [comment]
https://colabti.org/irclogger/irclogger_log/perl6?date=2019-03-21#l185

**Comment by jonathanstowe** [comment]
I'd just go with an explicit list on the right TBH.

I'll see if I can hack something together later.

**Comment by FCO** [comment]
sure! we can do a `sub infix:<< < >>(Red::AST::Lt $, $)`

**Comment by federico-razzoli** [comment]
I suggest to also support NOT BETWEEN.

Also, SQL standard and some DBMSs (like Postgres) support:

- BETWEEN SYMMETRIC
- NOT BETWEEN SYMMETRIC

The SYMMETRIC keyword sorts the operators, so that the lowest is always considered as the minimum.

For DBMSs that don't support this syntax, maybe Red could sort the operators before sending the query. But this can only be done if the operators are constant (not column names).

**Comment by FCO** [comment]
I think I'm almost there:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/99834/181667436-e6c970e9-8575-49b6-a849-9db6103705cf.png">

**Comment by jonathanstowe** [comment]
Looks good :+1:

**Comment by FCO** [comment]
I think that's working... Can anyone confirm?

**Comment by jonathanstowe** [comment]
I'll have to remember where it was I wanted to use this.
