### ISSUE TITLE
.^create record is extremely slow

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#147]
Could be that I do something wrong, but in my real-life case with two models linked by an `id` column adding four new records takes 25secs. Storing same records using direct `DB::Pg` `prepare`/`execute` API takes ... **0.03sec**!

**Comment by FCO** [comment]
Would you mind to share the code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
It would help a lot if you could share your code... In my simple test Im getting different results:

```
$ perl6 -MRed -e '
model Test { has Int $.a is column }
my $*RED-DB = database "Pg";
Test.^create-table: :if-not-exists;

my $start = now;
Test.^create: :42a;
say now - $start
'
0.019932
```

maybe this time is compiling your models? Does the 2nd time you run it takes all this time?

Thanks!

**Comment by vrurg** [comment]
I need time to golf it down to something sensible.

Profiling pointed me out at `AUTOGEN` method in class `Dummy`. This makes me think that at some point a huge number of calls to missing methods happens. But I'll try to find out more later today when get a nice and compact sample code.

**Comment by vrurg** [comment]
Ok, here is the code. Not sure if I can make it any shorter as I suspect the relations are involved.

I left the `$*RED-DB` initialization out of the scope. BTW, I don't see a reason for making `$!dbh` a private attribute because it'd be handy for certain operations we can't perform using Red itself. That's why the trick at the beginning – I wanted the code to do a fresh start on each run. Besides, I was receiving weird errors on table creation when the table already exists.

```
my $dbh = $*RED-DB.prepare('SELECT "OK"').statement;
$dbh.query('DROP TABLE IF EXISTS drecords');
$dbh.query('DROP TABLE IF EXISTS dtype');

model Records { ... }

model DType is table<dtype> {
    has Int $.id is serial;
    has Str $.type is column{ :unique };
    has Records @.records is relationship{ .dtype-id };

    method populate-data {
        my Set $d = self.^all.map( *.type ).Set;
        for <type1 type2 type3> -> $dt {
            self.^create: type => $dt unless $dt ∈ $d;
        }
    }
}

model Records is table<drecords> {
    has UInt $.id is serial;
    has Str $.info is column;
    has Rat $.value is column;
    has Int $.dtype-id is referencing{ DType.id };
}

DType.^create-table;
Records.^create-table;

DType.populate-data;

my $dt = DType.^find: type => 'type1';
my %data =
    rec1 => 1,
    rec2 => 42,
    rec3 => pi,
    rec4 => 0,
    ;

my $recs = $dt.records;

note "Trying Red";
my $rt = now;
for %data.keys -> $info {
    $recs.create: :$info, value => %data{$info};
}
note "Red done in ", $rt - now;

note "Trying Red, model direct";
my $dtype-id = $dt.id;
my $rtd = now;
for %data.keys -> $info {
    Records.^create: :$info, value => %data{$info}, :$dtype-id;
}
note "Red done in ", $rtd - now;

$dbh.query('DELETE FROM drecords');

note "Trying Pg";
my $pgt = now;
for %data.keys -> $info {
    my $db = $dbh.db;
    my $sth = $db.prepare('INSERT INTO drecords (info, value, dtype_id) VALUES ($1,$2,$3)');
    $sth.execute($info, %data{$info}, $dtype-id);
    $db.finish;
}

note "Pg done in ", $pgt - now;
```

**Comment by FCO** [comment]
For me it has ran almost instantly...

```$ perl6 create-slow.p6 
NOTICE:  table "drecords" does not exist, skipping
NOTICE:  table "dtype" does not exist, skipping
Trying Red
Red done in -0.12591512
Trying Red, model direct
Red done in -0.0945608
Trying Pg
Pg done in -0.01103759
```

**Comment by FCO** [comment]
I understood just now... ok, the create is 9 times slower than Pg... I’ll take a look at it...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
In my setup it's 180 times slower. I was previously using a branch separated off 0.0.3 tag. But the latest test was run against the latest master. Another possible source of problems is PostgreSQL 9.3 – the version used by QNAP. I'm gonna try a more recent version on one of my VMs to see if this changes anything.

**Comment by FCO** [comment]
and about the `$!dbh`, you can use `$*RED-DB.execute` and `$*RED-DB.prepare` instead...

**Comment by FCO** [comment]
```
$ cat create-slow.p6 
use Red;

my $*RED-DB = database "Pg";

$*RED-DB.execute('DROP TABLE IF EXISTS drecords');
$*RED-DB.execute('DROP TABLE IF EXISTS dtype');

model Records { ... }

model DType is table<dtype> {
    has Int $.id is serial;
    has Str $.type is column{ :unique };
    has Records @.records is relationship{ .dtype-id };

    method populate-data {
        my Set $d = self.^all.map( *.type ).Set;
        for <type1 type2 type3> -> $dt {
            self.^create: type => $dt unless $dt ∈ $d;
        }
    }
}

model Records is table<drecords> {
    has UInt $.id is serial;
    has Str $.info is column;
    has Rat $.value is column;
    has Int $.dtype-id is referencing{ DType.id };
}

DType.^create-table;
Records.^create-table;

DType.populate-data;

my $dt = DType.^find: type => 'type1';
my %data =
    rec1 => 1,
    rec2 => 42,
    rec3 => pi,
    rec4 => 0,
    ;

my $recs = $dt.records;

note "Trying Red";
my $rt = now;
for %data.keys -> $info {
    $recs.create: :$info, value => %data{$info};
}
note "Red done in ", $rt - now;

note "Trying Red, model direct";
my $dtype-id = $dt.id;
my $rtd = now;
for %data.keys -> $info {
    Records.^create: :$info, value => %data{$info}, :$dtype-id;
}
note "Red done in ", $rtd - now;

$*RED-DB.execute('DELETE FROM drecords');

note "Trying Pg";
my $pgt = now;
for %data.keys -> $info {
    my $sth = $*RED-DB.prepare('INSERT INTO drecords (info, value, dtype_id) VALUES ($1,$2,$3)');
    $sth.execute($info, %data{$info}, $dtype-id);
}

note "Pg done in ", $pgt - now;
$ perl6 create-slow.p6 
Trying Red
Red done in -0.08791503
Trying Red, model direct
Red done in -0.0547193
Trying Pg
Pg done in -0.006266575
```

**Comment by FCO** [comment]
A more complete list of ways of doing that (added a `.^create` passing an array of hashes representing Records):

```
$ cat create-slow.p6 
use Red;

my $*RED-DB = database "Pg";
#my $*RED-DEBUG = True;

$*RED-DB.execute('DROP TABLE IF EXISTS drecords');
$*RED-DB.execute('DROP TABLE IF EXISTS dtype');

model Records { ... }

model DType is table<dtype> {
    has Int $.id is serial;
    has Str $.type is column{ :unique };
    has Records @.records is relationship{ .dtype-id };

    method populate-data {
        my Set $d = self.^all.map( *.type ).Set;
        for <type1 type2 type3> -> $dt {
            self.^create: type => $dt unless $dt ∈ $d;
        }
    }
}

model Records is table<drecords> {
    has UInt $.id is serial;
    has Str $.info is column;
    has Rat $.value is column;
    has Int $.dtype-id is referencing{ DType.id };
}

DType.^create-table;
Records.^create-table;

my %data =
    rec1 => 1,
    rec2 => 42,
    rec3 => pi,
    rec4 => 0,
;

note "Trying Red create all";
my $rtall = now;
my @records = %data.kv.map: -> $info, $value --> Hash() { :$info, :$value };
DType.^create: :type<type1>, :@records;
note "Red create all done in ", $rtall - now;

$*RED-DB.execute('DELETE FROM drecords');
$*RED-DB.execute('DELETE FROM dtype');
DType.populate-data;

my $dt = DType.^find: type => 'type1';
my $recs = $dt.records;

note "Trying Red";
my $rt = now;
for %data.keys -> $info {
    $recs.create: :$info, value => %data{$info};
}
note "Red done in ", $rt - now;

note "Trying Red, model direct";
my $dtype-id = $dt.id;
my $rtd = now;
for %data.keys -> $info {
    Records.^create: :$info, value => %data{$info}, :$dtype-id;
}
note "Red done in ", $rtd - now;

$*RED-DB.execute('DELETE FROM drecords');

note "Trying Pg";
my $pgt = now;
for %data.keys -> $info {
    my $sth = $*RED-DB.prepare('INSERT INTO drecords (info, value, dtype_id) VALUES ($1,$2,$3)');
    $sth.execute($info, %data{$info}, $dtype-id);
}

note "Pg done in ", $pgt - now;
$ perl6 create-slow.p6 
Trying Red create all
Red create all done in -0.0905988
Trying Red
Red done in -0.06325835
Trying Red, model direct
Red done in -0.04742402
Trying Pg
Pg done in -0.01832506
```

**Comment by vrurg** [comment]
This was tricky. What is actually happening is you have `RETURNING *` in your `INSERT` statement which happens to catastrophically slow down `$dbh.query()`. No idea what exactly causes the problem (macOS client is the most likely source of problems), but explicit releasing of database connection is the solution, as you can see in PR #148.

**Comment by vrurg** [comment]
BTW, I missed the final version of your comment on different ways of solving the task. Unfortunately, in the real life application I'll be fetching records one by one making batch storing unreasonable. But your example is just fantastic, I didn't think this is possible! Though, what am talking about? DWIM in action!

Red is really the first ORM I do want to use. Absolutely stunning work of yours!

**Comment by vrurg** [comment]
Before closing this one I'd like to ask two off-topic questions. Both may end up in feature-request tickets.

Do you plan for transactions support?

Setting `$*RED-DB` manually is not the aesthetic approach. May be use a syntax sugar like this:

```
red-do {
    Model.^create: ...
}
```

If you have on objection, I would provide more detailed proposals.

**Comment by FCO** [comment]
Yes, I plan to create transactions (https://github.com/FCO/Red/issues/16).
I think I liked the `red-do`...

**Comment by FCO** [comment]
maybe a `red-do` could be an `given` that sets `$*RED-DB` instead of `$_`... but it would, probably, need a slang to make it beautiful `red-do "SQLite" { ... }` (I mean without the ",")

**Comment by FCO** [comment]
would you mind if I use the last version of your code as an example (https://github.com/FCO/Red/tree/master/examples)?

**Comment by vrurg** [comment]
You're very welcome, for sure! I think your edition with `$*RED-DB.execute` is the best candidate for this.

**Comment by FCO** [comment]
is it good to closing?

**Comment by vrurg** [comment]
Yes, I'll close it now.
