### ISSUE TITLE
.^all.map results in 'type cannot unbox to a native string' error

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#149]
Here is the code reproducing the issue:

```
model MyModel {
    has Int $.id is serial;
    has Str $.data is column;
}
'test.sqlite'.IO.unlink;
my $*RED-DB = database 'SQLite', database => 'test.sqlite';

MyModel.^create-table;

for <line1 line2 line3> -> $data {
    MyModel.^create: :$data;
}

my %h = MyModel.^all.List.map: { .data => .id };
dd %h;
%h = MyModel.^all.map: { .data => .id };
dd %h;
```

Note that `.List` fixes the problem. Preliminary analysis reveals that `.data` is `Str` in the first case (which is expected) but happens to be `Red::Column` type (not even an instance) in the second case.

**Comment by FCO** [comment]
We have to create a `multi infix:<< => >>(Red::AST, Red::AST)` to fix that... but it should fail back to `.Seq.map`...

**Comment by jonathanstowe** [comment]
Yeah I was wondering about the fallback to ```.Seq.map``` for a while now.  It would make composing code that doesn't know that it was going to be used on a ```Red::Model``` much easier :)

**Comment by FCO** [comment]
@vrurg that's not a fix, but just to let you know that you can do something like:

```perl6
MyModel.^all.classify: *.data
```

**Comment by vrurg** [comment]
Yet, it's throws later. A kind of action at distance.

Because I needed a chained action, this worked for me too: `MyModel.^all.List.map(...).further.actions`.

**Comment by FCO** [comment]
`.classify` returns a Red::ResultAssociative where you can continue running methods...

**Comment by vrurg** [comment]
Could be that I'm already too tired and missing a point here, but to get the result of the first line (the one with `.List`) I need to do:

```
%h = MyModel.^all.classify({ .data }).map: { .key => .value.head.id };
```

because the values in `Red::ResultAssociative` are `MyModel::ResultSeq`.

**Comment by FCO** [comment]
I was thinking on something like:
```perl6
my %hash := MyModel.^all.classify: *.data;
# and using it
%hash<bla>.head.id
```

It will (probably) run only 1 query with limit 1 and where data == ‘bla’...

**Comment by FCO** [comment]
But it can not be the best way to do what you want...

**Comment by vrurg** [comment]
My original point was to cache locally a little table. So, I'm ok with mapping into hash.

I would like to go off topic a bit. in #150 I provided a code sample. It is based on a tree structure where parent-child relation is defined in a separate mapping table. In that model to reference a parent from a child I would need to do:

```
$my-model.parent.parent
```

because I must first get the mapping record and then get actual `MyModel` parent. Is it possible to shorten the path and have `MyModel` entry directly in `MyModel` itself? Kind of:

```
model MyModel {
    ...
    has MyModel $.parent is relationship { MyModelRel.parent-id } is field { MyModelRel.parent };
}
```

The syntax is obviously imaginative.

**Comment by FCO** [comment]
I think the easiest way to do that would be with a method...
```perl6
has ParentModel $!parent is relationship{ .parent-id };
method parent { $!parent.parent }
```

**Comment by FCO** [comment]
did it work for you?

**Comment by vrurg** [comment]
It did, thank you! Though later I decided that a simple tree structure with 'parent-id' works better. And this raised another question. 

```
model MyModel is nullable {
    has UInt $.id is serial;
    has Str $.text is column{ :!nullable };
    has UInt $.parent-id is referencing{ MyModel.id };
    has MyModel $.parent is relationship{ .parent-id };
    has MyModel @.children is relationship{ .parent-id, .id };
}
```

Is there a way to declare `@.children` using `relationship`? I found a trait where `relationship` is expected to be an array of two elements. Perhaps this is what I'm looking for, but can't determine how it works.

**Comment by FCO** [comment]
The trait with 2 was for % relationships for example: https://github.com/FCO/Red/issues/17#issuecomment-414101155

Simply using parent-I’d doesn’t work? (Sorry, I’m not with my computer now...)

```perl6
has ::?CLASS @.children is relationship{ .parent-id };
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
That would be the parent record. The solution became possible with the trait signature fix and it looks like this:

```
model MyModel is nullable {
    has UInt $.id is serial;
    has Str $.text is column{ :!nullable };
    has UInt $.parent-id is referencing{ MyModel.id };
    has MyModel $.parent is relationship{ .parent-id };
    has MyModel @.children is relationship( { .parent-id }, { .id } );
}
```

**Comment by FCO** [comment]
Not using @...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
```
$ perl6 -MRed -e '

my $*RED-DB = database "SQLite";

model MyModel is nullable {
    has UInt $.id is serial;
    has Str $.text is column{ :!nullable };
    has UInt $.parent-id is referencing{ MyModel.id };
    has MyModel $.parent is relationship{ .parent-id };
    has MyModel @.children is relationship{ .parent-id };
}

MyModel.^create-table;

for <t1 t2 t3> -> $text {
    MyModel.^create: :$text;
}

my $t1 = MyModel.^find: text => "t1";
for <a b c> -> $t {
    $t1.children.create: :text("t1$t")
}                                                    
 
my $t1b = MyModel.^find: text => "t1b";
                                       
say $t1b.parent.text;
say $t1.children;
                 
'
t1
(MyModel.new(id => 4, text => "t1a", parent-id => 1) MyModel.new(id => 5, text => "t1b", parent-id => 1) MyModel.new(id => 6, text => "t1c", parent-id => 1))
```

**Comment by vrurg** [comment]
Hm, reasonable. Thanks for the correction!

Now I wonder what does the two-block version of the trait does? The one I used in my code.

**Comment by FCO** [comment]
It was for associative many-to-many relationships... https://github.com/FCO/Red/issues/17#issuecomment-414101155

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
Good to know, thanks! From the syntax point of view, why not:

```
has $.field is relationship{ .one-id, .second-id }
```

Why the complication with the code blocks list?

**Comment by FCO** [comment]
now N-M relationships ar handled with 2 1-N relationships and 1 method, for example (the tags and the posts methods):

```raku
use Red;

model PostTag {...}

model Post {
	has UInt    $.id        is serial;
	has Str     $.title     is unique;
	has PostTag @.post-tags is relationship{ .post-id };
	method tags { @.post-tags>>.tag }
}

model Tag {
	has Str $.name          is id;
	has PostTag @.post-tags is relationship{ .tag-id };
	method posts { @.post-tags>>.post }
}

model PostTag {
	has UInt $.post-id is column{ :id, :references{ .id },   :model-name<Post> };
	has Str  $.tag-id  is column{ :id, :references{ .name }, :model-name<Tag>  };
	has Post $.post    is relationship{ .post-id };
	has Tag  $.tag     is relationship{ .tag-id  };
}
```
