### ISSUE TITLE
red-do/red-defaults

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#153]
The current way of defining active database driver and its parameters isn't the prettiest one:

```
my $*RED-DB = database ...;
```

I would like to propose simple syntax sugar similar to the existing `supply`, `react`, etc. blocks. The most simple form would look like:

```
red-do {
    MyModel.^find: ...;
}
```

Where `red-do` would set the $*RED-DB for the user. The database object would be passed as block's topic:

```
red-do {
    .execute($SQL-query);
}
```

or 

```
red-do -> $db {
    $db.execute($SQL-query);
}
```

Where would `red-do` get database parameters from? Considering that most applications most of the time work with the same database, it would be sufficient to set them once. This would require additional routine `red-defaults`:

```
red-defaults
    :Pg(
        host => 'hostname',
        dbname => 'database',
        :default,
    ),
    :SQLite(
        database => 'file.sqlite',
    );
```

If only one driver defined with `red-defaults` then we use it. If more drivers are mentioned then one of them can have `:default` adverb. So, the common use case would look like:

```
red-defaults :SQLite(...);
...
red-do {
    ...
}
```

Which is much more elegant, to my view.

`red-do` would also take parameters. In a simple case it's the driver we want to use:

```
red-do Pg => {
    ...
}
red-do 'SQLite', {
    ...
}
```

This would be the required form if multiple default drivers are defined but none declared as `:default`.

`red-do` could also receive driver parameters:

```
red-do 'Pg', host => 'host', {
    ...
}
```

The pre-defined defaults are not involved with this format. Another significant side effect of parameterized call is creation of a new database object whereas all other variants would re-use the same driver object pre-cached on the first `red-do` call.

Also, for applications started as a single method call like `App.run` this would be the preferable form of accessing their only database connection:

```
red-do 'Pg', host => ..., user => ..., password => ..., {
    App.run
}
```

`red-do` must return what it's code block returns.

**Comment by FCO** [comment]
maybe we could add a way to configure the possible drivers with config files...

**Comment by vrurg** [comment]
That's another possible solution too, but that'd be totally optional. In general, most applications have their own configurations one or other way. So, I wouldn't waste time on this any time soon.

**Comment by vrurg** [comment]
Oh, and answering your comment on `red-do` in #147 – I don't think slang would worth the time spent on it. One extra comma means almost nothing here. The most common use I expect to be just plan `red-do { ... }` as I can't recall a single application that would deal with different databases. SQLite in addition to a SQL server is the most realistic scenario here.

And, as you see, I was thinking of setting `$*RED-DB` as the primary job for `red-do` in first place. Topicalizing it is just a minor side effect of passing it as the only block parameter.

**Comment by FCO** [comment]
Maybe we should add the concept of `read` and `write` databases... so we could do something like:

```perl6
red-defaults :Pg(:host<host1>, :write), :Pg(:host<host2>, :read);
```

and that would run selects on host2 and insert, delete, update, etc on host2...
or maybe another syntax...

**Comment by vrurg** [comment]
Oh, that's what I had implemented in one of my work projects to support MySQL master-slave clustering. That would have huge advantage on such setups!

The only thing to be considered is possible race conditions when write is not synced to a slave yet but `SELECT` is already requested. Even though this is up to a user to consider, but Red is doomed to be used by newbies/juniors who won't go much into such details. Perhaps **A HUGE WARNING IN BOLD** is what'd be needed in the documentation.

**Comment by FCO** [comment]
Just to let you know, Im doing my first tests about this proposal...
If you want to know how it is going so far:

```
$ perl6 -I. -e '
use Red \<red-do>;
model M is table<mmm> { has Str $.bla is column }

red-defaults "SQLite";

red-do {
   M.^create-table: :if-not-exists;
   M.^create: :bla<ble>;

   say M.^all
}
'
(M.new(bla => "ble"))
```

**Comment by vrurg** [comment]
Looks great! Thank you!

**Comment by FCO** [comment]
```
$ perl6 -I. -e '
use Red \<red-do>;

model M is table<mmm> { has Str $.bla is column }

red-defaults :bla["SQLite", :default, :database<./bla.db>], :ble["SQLite", :database<./ble.db>];

red-do
    { say 1, " -> ", $*RED-DB },
    "ble" => { say 2, " -> ", $*RED-DB },
    "bla"|"ble" => { say 3, " -> ", $*RED-DB },
;
'
1 -> Red::Driver::SQLite.new(database => "./bla.db")
2 -> Red::Driver::SQLite.new(database => "./ble.db")
3 -> Red::Driver::SQLite.new(database => "./bla.db")
3 -> Red::Driver::SQLite.new(database => "./ble.db")
```

**Comment by FCO** [comment]
its on experimental mode, so, you must to use `use Red \<red-do>` to use it...

**Comment by vrurg** [comment]
I like the approach to `red-defaults`. Don't think it'd be of much use for applications working with SQL-servers, but it is really handy for SQLite where multiple databases could be in use. Hopefully, it's still possible to have `red-defaults "Pg", ...`.

**Comment by FCO** [comment]
yes, it is...

**Comment by FCO** [comment]
im thinking of something like:
```perl6
red-db :read-from<slave>, :write-on<master>, { ... }
```

what do you thing?

**Comment by MattOates** [comment]
So not sure I agree with a lot of the discussion here. There are *many* applications for multi db, and special casing one for reading and writing seems quite quirky to me. Instead of using special cased functions surely something more like a repository pattern for the DB connections or a parametric singleton class with a basic `given` block for topicising the connection is cleaner?

**Comment by vrurg** [comment]
@FCO maybe `:ro` and `:rw`? Otherwise looks ok.

@MattOates may you provide a sample, please? Would be interesting to see it.

**Comment by FCO** [comment]
But isn't `red-db` just like that?

**Comment by vrurg** [comment]
```
red-defaults 
   :ro-server["MySQL", :host<master>, ...],
   :rw-server["MySQL", :host<slave>, ...];

red-do :rw<rw-server>, {
    MyMode.^create: ...;
}
red-do :ro<ro-server>, {
    my $rec = MyModel.^load: :$id;
}
```

Looks neat, is functional. Allows for centralized configuring of database parameters while the code actually using it is abstracted of the particular server parameters. What else is missing here?

**Comment by FCO** [comment]
I was thinking of doing:

```perl6
red-do :write-on<master>, :read-from<slave>, {
   MyModel.^create: ...;
   MyModel.^load: ...;
...
```

And that would send the selects to the slave and the insert, update, etc to the master...

I agree this is just one way to use multiple databases, but it is the most used way (at least by me)... I don’t know if it would be a problem facilitating it...


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
It was just quick typing on my side. In either case, this increases the abstraction level which is good for the code. My only point is that I'm lazy and `:rw`, `:ro` looks way more attractive to my eyes.

**Comment by FCO** [comment]
@MattOates is your problem with the whole proposal or only with the read/write?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
@MattOates ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
I was wondering... if we set the `red-defaults`, we don't need `red-do`.
I mean: we could do every query try to use $*RED-DB, but if it's not set up, do what `red-do` would do... `red-do` can still exist to cases where you want to use not the default driver...

**Comment by vrurg** [comment]
You need to declate `$*RED-DO` somewhere and `red-do` is the place. You can inject it into globals, of course, but that's far from the best or elegant solution.

**Comment by FCO** [comment]
```
$ perl6 -MTest -I. -e 'use Red \<red-do>;
model Bla { has UInt $.id is serial }
red-defaults "SQLite", :database<./bla.db>;

Bla.^all.say
'
(Bla.new(id => 1) Bla.new(id => 2) Bla.new(id => 3) Bla.new(id => 4) Bla.new(id => 5) Bla.new(id => 6) Bla.new(id => 7) Bla.new(id => 8) Bla.new(id => 9) Bla.new(id => 10) Bla.new(id => 11))
```

**Comment by vrurg** [comment]
Looks undoubtedly good! Exceptionally great for fast scripting.

Perhaps, I would argue to the implementation and suggest using `get-RED-DB` anywhere `$*RED-DB` is used. Perhaps cache it with a local variable if used multiple times over a scope. It just looks somewhat more error-proof to me this way. But that's me just grumbling. ;)

Thanks for your efforts!

**Comment by FCO** [comment]
Yes, that would make much more sense! :) I’ll change it tomorrow after the day work...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCO** [comment]
Maybe we could use it (and the difference between write and read) and create a way to cache query results... Something like `Red::Driver::Cache::Redis` or `Red::Driver::Cache::MemCached`

**Comment by vrurg** [comment]
I was thinking about caching, but happened to be absolutely unprepared to so fast development of the situation. But that'd be subject for another issue. This one seems to be ready for closing.

**Comment by FCO** [comment]
I've added some tests for it, and also added a `red-defaults-from-config`...

**Comment by FCO** [comment]
Maybe cache could looks like this: https://github.com/FCO/Red-Driver-Cache-Redis

**Comment by vrurg** [comment]
I didn't think much about caching (BTW, indexing is what I did think about). So, I those are on-the-fly thoughts.

```
red-defaults
    :db1("SQLite", ...),
    :default("Cache::Redis", :database<db1>),
```

Since the cache driver is transparent, the rest is irrelevant, I think.

**Comment by FCO** [comment]
```
$ perl6 -I. -MRed -MRed::Driver::Cache::Redis -e'

model Bla {
    has UInt $.id is serial;
    has Str  $.bla is column;
}

my $*RED-DB = database "Cache::Redis", :driver-name<SQLite>;
Bla.^create-table: :if-not-exists;

Bla.^create(:bla(("a" xx Bool.pick) ~ "blablabla " ~ ++$)) for ^20;

my $*RED-CACHE-REDIS-DEBUG = True;
say Bla.^all.grep: *.bla.starts-with: "a";
say Bla.^all.grep: *.bla.starts-with: "a";
'
Caching on CACHED_SELECT:bla.id|bla.bla:FROM:bla:WHERE:bla.bla_like_a%
(Bla.new(id => 4, bla => "ablablabla 4") Bla.new(id => 6, bla => "ablablabla 6") Bla.new(id => 10, bla => "ablablabla 10") Bla.new(id => 13, bla => "ablablabla 13") Bla.new(id => 15, bla => "ablablabla 15") Bla.new(id => 17, bla => "ablablabla 17") Bla.new(id => 20, bla => "ablablabla 20"))
Got from cache: CACHED_SELECT:bla.id|bla.bla:FROM:bla:WHERE:bla.bla_like_a%
(Bla.new(id => 4, bla => "ablablabla 4") Bla.new(id => 6, bla => "ablablabla 6") Bla.new(id => 10, bla => "ablablabla 10") Bla.new(id => 13, bla => "ablablabla 13") Bla.new(id => 15, bla => "ablablabla 15") Bla.new(id => 17, bla => "ablablabla 17") Bla.new(id => 20, bla => "ablablabla 20"))
```

**Comment by vrurg** [comment]
Just in case: I wouldn't be able to closely follow the development because need to focus on my rakudo build revamp project. But I am watching anyway!

**Comment by FCO** [comment]
Maybe we should merge this with the migration idea (https://github.com/FCO/Red/issues/15) of a code that should run before the migration, another to run while it's running and one more after it's complete...

**Comment by vrurg** [comment]
Briefly read through the migration thread. Frankly saying, not sure how these two are linked to each other?
