### ISSUE TITLE
Question/proposal on :nullable

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#157]
I wonder why Red needs explicit `nullable` adverb? Is there any problem to use definedness of column type?

```
has Str:D $.col1 is column; # NOT NULL
has Str $.col2 is column; # nullable
```

**Comment by FCO** [comment]
It was the original way to do that...
But it’s very common someone want a nullable attribute for a not nullable column...
You may need ‘.new’ an obj, and populate a nullable attribute/not nullable field just before the `.^save`.
And that way, the default would be not nullable columns, that is not a good idea...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
Very good point. Ok, thank you!
