### ISSUE TITLE
Pre-compilation related failure in .^all.grep

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#158]
The problem occurs when models are defined in a module and have a relationship established.

Here is `TestRed.pm6` test module code:

```
use v6.d;
unit module TestRed;
use Red;

model MyModel is table<test_mymodel> is export {
    has UInt $.id is serial;
    has Str $.field is column;
}

model Related is table<test_related> is export {
    has UInt $.m-id is referencing{ MyModel.id };
    has Str $.descr is column;

    has MyModel $.m is relationship{ .m-id };
}
```

and the test script:

```
#!/usr/bin/env perl6
use lib '.';
use TestRed;
use Red <red-do>;

red-defaults 'Pg',
            host => 'servant.local',
            user => 'bo-trading',
            password => 'mivdiCruHa',
            dbname => 'bo-trading-test',
            ;

red-do {
    .execute('DROP TABLE IF EXISTS test_mymodel CASCADE');
    .execute('DROP TABLE IF EXISTS test_related CASCADE');
}

MyModel.^create-table;
Related.^create-table;

for <a b bc cd> {
    my $m = MyModel.^create: field => $_;
    Related.^create: m-id => $m.id, descr => "Description 1 of $_";
    Related.^create: m-id => $m.id, descr => "Description 2 of $_";
}

my $*RED-DEBUG = True;
my @r = Related.^all.grep: *.m.field eq 'bc';

say @r;
```

It results in 

>`Cannot invoke this object (REPR: Null; VMNull)`

exception. `no precompilation` in `TestRed` workarounds the problem.

From my experience, this is caused by a bug in rakudo. But sometimes it is possible to cheat a little to get around the bug.

**Comment by vrurg** [comment]
@FCO Somehow my previously written comment didn't make it into this issue.

I have fixed the bug in MoarVM which caused this problem. Unfortunately, I can't make a proper test for now. Would it be possible for you to test and confirm that things work as expected now?

**Comment by FCO** [comment]
I’ll try it as soon as I come back home...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
