### ISSUE TITLE
Change of an id field is not possible

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#159]
Consider a model:

```
model MyModel {
    Str:D $.name is id is rw;
}
```

If at some point one would try to:

```
my $m = MyModel.^find: name => "a name";
$m.name = "changed name";
$m.^save;
```

this won't change the record in the database. This is caused by Red taking the new value of `.name` and trying to update the record with it:

```
UPDATE my_model SET name = 'changed name' WHERE name = 'changed name'
```

Perhaps it would make sense to preserve the original value of an `id` field when a record is fetched from database.

**Comment by FCO** [comment]
@vrurg would you mind to test if it was fixed, please?

**Comment by vrurg** [comment]
Will see if I can tomorrow but unfortunately can't promise anything for now. So overloaded that had to postpone the project where I used Red.

**Comment by FCO** [comment]
@vrurg ene news on this?

**Comment by vrurg** [comment]
Oh my... I totally forgot about this one... The bad part is that to do a proper test I need to get the  problem with exports closed first. And this one depends on testing rakudo/rakudo#3081 with Blin against ecosystem modules which can only be done by AlexDaniel...

**Comment by vrurg** [comment]
It seems like I can do no better testing now as you would. I have changed DB structure a while ago and this construct is not used anymore in my code. Any test I would write now would be a duplicate of the initial request. So, can be closed too. 

Thank you!
