### ISSUE TITLE
Transaction?

### ISSUE THREAD

**Issue by FCO** [FCO/Red#16]
```perl6
Red.transaction: {
   ... # code that will run inside of the transaction
       # die to rollback
}
```

**Comment by FCO** [comment]
transaction should be on the schema class if we decide to create one...

**Comment by jonathanstowe** [comment]
At it's simplest this could be:

```perl6
method transaction(&block) {
    CATCH {
        default {
             $*RED-DB.execute: "ROLLBACK";
             $_.rethrow;
        }
    }
    $*RED-DB.execute: "BEGIN WORK";
    &block.();
    $*RED-DB.execute: "COMMIT";
}
```

**Comment by FCO** [comment]
I was thinking of something like this:

```perl6
method transaction(&block, :$db = $*RED-DB) {
    my $*RED-DB = $db.transaction;
    CATCH {
        default {
            $*RED-DB.rollback;
            .rethrow
        }
    }
    block;
    $*RED-DB.commit;
}
```

And each driver would implement it...

**Comment by santec** [comment]
There are things that it would be nice to support. Not all of them are important and I don't know what effort it requires. I'm listing these as ideas so one day someone can find this list and agree with part of it.

Standard:
- Isolation level
- Savepoints

MySQL:
- START TRANSACTION READ ONLY
- START TRANSACTION WITH CONSISTENT SNAPSHOT
- COMMIT AND CHAIN
- COMMIT AND RELEASE

PostgreSQL:
- READ ONLY
- [NOT] DEFERRABLE

SQLite:
- BEGIN [ DEFERRED | IMMEDIATE | EXCLUSIVE ] TRANSACTION

**Comment by santec** [comment]
When a deadlock occurs, the typical solution is simply to retry the transaction. So, it would be nice if Red:

- remember the queries until commit
- recognize a deadlock error (1213 in MySQL)
- rollback
- retry the whole transaction (once by default)

**Comment by vrurg** [comment]
I would like to make a proposal on syntax of the transaction which would influence the semantics too. 

Instead of having `transaction` routine as a database object method, it could just be a routine and all it would do is raise a global transaction flag:

```
transaction {
    my $*RED-DB = database ...;
    MyModel.^create: ...;
}
```

Internally it could be as simple as:

```
sub transaction (&block) {
    my $*RED-IN-TRANSACTION = True;
    block;
    for all-transactions -> $transaction-handler {
        $transaction-handler.commit
    }
    CATCH {
        default {
            for all-transactions -> $transaction-handler {
                $transaction-handler.rollback
            }
        }
    }
}
```

The magic would happen in statement processing, where before actually executing a statement, a Red database object would detect if `$*RED-IN-TRANSACTION` is set, start a transaction and register a handler for it. 

The advantage of this approch is support for multiple logically linked transactions (a meta-transaction?) performed on different database objects. Yet, there be no extra cost on performance if no statement has been issued because no real transactions would be initiated.

**Comment by FCO** [comment]
I think I didn't get the meta-transaction idea... could you explain a little more and/or give me some samples/use cases, please?

**Comment by jonathanstowe** [comment]
You would need to be careful about nesting transactions as different RDBMS have different behaviour for nested transactions.  For instance within the same connection the Postgres will ignore subsequent ```BEGIN```   statements and a ```ROLLBACK``` will rollback to the first begin.  You'd handle the nested behaviour using "savepoints".

**Comment by vrurg** [comment]
@FCO nothing special. I'd use `red-do` syntax to simplify demo:

```
transaction {
    red-do 'Pg' {
        MyModel.^create: ...;
    }
    ...
    red-do 'MySQL' {
        AnotherModel.^create: ...;
    }
}
```

If `MySQL` block fails – what's done in `Pg` will rollback too. This way if I have logically linked operations to be performed in both DBs – they'd be done almost like a single transaction.

**Comment by vrurg** [comment]
@jonathanstowe this would be something to be handled by the drivers, wouldn't it? Alternatively, if side effects of the nesting are too significant, the construct itself could either warn or even die if detects such situation.

**Comment by FCO** [comment]
`red-do` accepts a `:transaction` adverb.
