### ISSUE TITLE
Incorrect handling of .map over a relationship

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#169]
Looks like a problem similar to #168 . Here is the code:

```
use v6;
use Red <red-do>;

red-defaults 'SQLite', :database<./test.sqlite>;

model Test {
    has UInt $.id is serial;
    has Str $.name is column;
    has UInt $.parent-id is referencing{ Test.id };

    has Test $.parent is relationship{ .parent-id };
    has Test @.children is relationship{ .parent-id };

    method rc {
        my $sfx = "";
        note "RC on ", self.WHAT, ", defined: ", self.defined;
        note "ID ", self.id, ", children: ", self.children.elems;
        with self {
            if .children {
                $sfx = "[" ~ .children.map( *.rc ) ~ "]"
            }
        }
        self.name ~ $sfx
    }
}

red-do {
    .execute: "DROP TABLE test";
}
Test.^create-table: :if-not-exists;

my $parent = Test.^create: :name("parent");

for ^10 {
    my $c = Test.^create: :name("child$_"), :parent-id($parent.id);
    # for 'a'..'d' {
    #     Test.^create: :name("subc$_"), :parent-id($c.id);
    # }
}

my $p = Test.^load: id => $parent.id;

my @c;
note "Parent has ", $p.children.elems, " children";
# gather/take works
@c = gather {
        take .rc for $p.children
};
say @c;
# map fails, defined is false
@c = $p.children.map: { note "in map, defined? ", .defined; .rc };

say @c;
```

When iterating over children with `map` children are not loaded from the DB and just typeobjects are passed into `map` code. Looks like the problem is quite persistent. If you uncomment the inner loop of database data filling (the a..d one), method `rc` would attempt to map over a child children effectively failing too.

I have certain suspicion that similar problem could affect grep, but not really sure about it.

**Comment by FCO** [comment]
@vrurg I still don't know how to make it work... while it's not fixed, could you try using `.children.Seq.map( *.rc )` this will convert the Red::ResultSeq to a Seq (running the query) and than run `map`...

**Comment by vrurg** [comment]
Did I report this already? Oh my memory... Sorry!

**Comment by vrurg** [comment]
Of course, `.Seq` works and I remember you telling me this previously. Ok, no sense to keep a duplicate of #149, closing.

**Comment by FCO** [comment]
it is the same problem as https://github.com/FCO/Red/issues/149
