### ISSUE TITLE
Feature request: Model initialization

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#170]
I have implemented a model for a config which does `Associative` and can be used as a hash. I.e.:

```
my $cfg = DBConfig.^load: id => 0
$cfg<foo> = "The Question!";
$cfg<foo>.say; # The Question!
```

There is a minor issue with this approach:

```
$cfg = %()
```

doesn't wipe the config, it assigns empty hash to `$cfg`, obviously. The right usage would be:

```
my %cfg is Config;
```

The problem is that I can't do:

```
my %cfg is DBConfig = .^load: id=>0;
```

Because then I need a method `STORE` which would somehow setup an already existing object. I tried to override method `new` but `new-with-id` doesn't work for me. Perhaps I'm missing something?

BTW, it doesn't worth separate ticket: in `MetamodelX::Red::Model` you apply a dummy role with `method TWEAK`. It must be `submethod` or some weird things might happen.

**Comment by FCO** [comment]
Would you mind to share your code?

**Comment by vrurg** [comment]
https://gist.github.com/vrurg/f5c8dfe909e890da975de2d5f380bc4f

**Comment by vrurg** [comment]
Note that there is no any initialization for now. To support:

```
my %cfg is BO-Config = BO-Config.^load: id => 0;
```

I need method `STORE` which would accept a pre-loaded record.

To have default initialization I tried:

```
method new { self.^new-with-id: { id => 0 } }
```

But it cannot match signature. 

```
method new { self.^new-with-id: 0 }
```

Just freezes.
```

**Comment by vrurg** [comment]
**UPD** I found `set-id` method which allows to use `STORE`:

```
method STORE (BO-Config:D $src) {
    self.^set-id: $src.id
}
```

That's good enough for now. Perhaps if add something like:

```
    self.TWEAK-MODEL(|c)
```

into the `TWEAK` method it would be good enough to use it for startup initialization to defaults.

**Comment by FCO** [comment]
should it be closed?

**Comment by vrurg** [comment]
I didn't test it yet, but I foresee no problems with such a simple change. Closing.

Thanks!
