### ISSUE TITLE
Feature request: allow for run-time table name change.

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#173]
Make it possible for a model to change its table name by a user at run-time. Proposed syntax would be:

```
Model.^table( "new_name" );
```

Considering that this approach would change the table name globally conflicts are possible if third-party modules are would be willing to use own tables for the same published model. I.e. lets assume there is a module `Red::DBHash` providing a hash mapped onto a table. There're modules `Foo` and `Bar` published on CPAN too. Both are using `Red::DBHash` but for different purposes. Both would need their own tables.

To resolve this situation a method `new_model` could be provided which would return a run-time created model type:

```
my \Model2 = Model.^new_type(:table<model2>);
```

Unless undocumented method `.^alias` does the same.

**Comment by vrurg** [comment]
BTW, it turns out there is no good way to get model's table name in the user land. Attribute `table` is public, but it's accessor isn't installed because method `table` exists. Method `table` always sets table name from the type supplied. Thus it would override any possible custom table name.

I think the solution is in making `table` a `multi` with no params (return only), typed `(Mu:U \type)`, and `(Str:D $name)` for this request.

**Comment by FCO** [comment]
@vrurg Wha do you think of this solution?

```
% perl6 -I. -MRed -e '
my $*RED-DB = database "SQLite"; my $*RED-DEBUG = True;
model Bla { has UInt $.a is id }
Bla.^table = "not_bla";
Bla.^create-table
'
SQL : CREATE TABLE not_bla(
   a integer NOT NULL primary key 
)
BIND: []
```

**Comment by vrurg** [comment]
Looks absolutely reasonable. Thanks!

**Comment by FCO** [comment]
Thanks!
