### ISSUE TITLE
Document `database`

### ISSUE THREAD

**Issue by FCO** [FCO/Red#191]
It is currently not documented. Features should be documented on the [wiki](https://github.com/FCO/Red/wiki). Feel free to create a new wiki page if you cannot find an existing page that is suitable.

**Comment by Altai-man** [comment]
It is now documented at https://github.com/FCO/Red/blob/master/lib/Red/Database.pm6
Along with future explanations in other documents (e.g. tutorials). Please, describe what else can be mentioned to close the issue.

**Comment by FCO** [comment]
Thank you very much!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
