### ISSUE TITLE
Document trait `is nullable`

### ISSUE THREAD

**Issue by FCO** [FCO/Red#274]
the model's is `nullable` and the column's `is nullable`.

It is currently just mentioned on documentation. Features should be documented on the [wiki](https://github.com/FCO/Red/wiki). Feel free to create a new wiki page if you cannot find an existing page that is suitable.

**Comment by Altai-man** [comment]
Closed with https://github.com/FCO/Red/pull/355

**Comment by FCO** [comment]
Thanks!
