### ISSUE TITLE
Find a better way to document it

### ISSUE THREAD

**Issue by FCO** [FCO/Red#325]
Remove the big snippet from the beginning of the README, and refactor it.

**Comment by JJ** [comment]
Maybe eliminate all SQL comments? Or put them somewhere else?

**Comment by FCO** [comment]
but where?

**Comment by Altai-man** [comment]
1)I see that pieces of this snippet are already deleted.
2)With more tutorials written we can remove those chunks of code with time, so in a way we already have a better way to document things.
