### ISSUE TITLE
Document the depreciation will occur on :api<2>

### ISSUE THREAD

**Issue by FCO** [FCO/Red#340]
On `:api<2>` this
```perl6
has $!ref is referencing{ Model.id }
```
Will be deprecated in favor of
```perl6
has $!ref is referencing( *.id, :model<Model> )
```
It will make better joins possible...

It is currently not documented. Features should be documented on the [wiki](https://github.com/FCO/Red/wiki). Feel free to create a new wiki page if you cannot find an existing page that is suitable.

**Comment by JJ** [comment]
Created [here](https://github.com/FCO/Red/wiki/API-Deprecation). I don't know if that closes the issue. It would have been much better if simple documents in Pod6 or Markdown had been used; that way we can easily reference them from commits.

**Comment by FCO** [comment]
Thanks!
Xliff and sena_kun has proposed to documenting on code the API documentation and generate MD from that... but how to do that from !API doc?
