### ISSUE TITLE
Document `$*RED-COMMENT-SQL`

### ISSUE THREAD

**Issue by FCO** [FCO/Red#343]
`$*RED-COMMENT-SQL` is currently not documented. Features should be documented on the [wiki](https://github.com/FCO/Red/wiki). Feel free to create a new wiki page if you cannot find an existing page that is suitable.

**Comment by Altai-man** [comment]
Documented at https://github.com/FCO/Red/wiki/Dynamic-Variables#red-comment-sql, can be closed? What else should be added?

**Comment by FCO** [comment]
Yes... I was just not sure about my english, so I left it there to any review... sorry, thanks!
