### ISSUE TITLE
Somme comments on Dynamic variables

### ISSUE THREAD

**Issue by JJ** [FCO/Red#350]
* *Its usage will be substituted*: When? Why? Does it mean it will be deprecated?
* Where are the comments inserted by $*RED-COMMENT-SQL? Is it used in conjunction with some other variable?

**Comment by FCO** [comment]
- it will not be deprecated, but will not be stimulated. It will occur on `:api<2>`, when `red-do` will not be experimental anymore.
- to see the comments, you can use in conjunction with `$*RED-DEBUG`, but it’s main purpose it make it easy, to seeing a db log, find where on code that query was run...

**Comment by FCO** [comment]
`:api<2>` is out. We should “fix” the docs!
