### ISSUE TITLE
README.md Synopsis redeclares symbols instead of using different ones

### ISSUE THREAD

**Issue by irced** [FCO/Red#365]
# README.md :: Synopsis.pl6
https://github.com/FCO/Red#synopsis

# Potential difficulties: Redeclaration of symbol '$post1'
`51: my Post $post1 = Post.^load: :42id; `
`65: my Post $post1 = Post.^load: 42;  `

# suggestion solution
`51: my Post $post2 = Post.^load: :42id; `
`65: my Post $post3 = Post.^load: 42;  `

**Comment by FCO** [comment]
Fixed
