### ISSUE TITLE
Aliases' survey

### ISSUE THREAD

**Issue by FCO** [FCO/Red#406]
Hi there!

@Xliff [has suggested](https://github.com/FCO/Red/pull/405) creating some aliases for `.^all.grep` and `.^all.map`, respectlly `.^where` and `.^update`.

Remembering that `Model.^all` represents all Model's database items. And returns a `ResultSeq` that has (or will have) all `Seq`'s methods to generate SQL queries when needed. And the idea behind **Red** is that you could use it without needing to learn a lot of ORM's syntax, and use mostly Raku's syntax.

But it's hard for me to believe the users would prefer to learn 2 more meta-method names instead of only knowing 1 (`.^all`) and using its return as a common `Seq`.

Another problem is that `.^all.map` is not used only for updating... it's only an update operation if one change values inside of its block, and calls `.save` on its return.

So, I'd like to know the other user's opinions on that.

What you guys would prefer?

**Comment by FCO** [comment]
Create the `.^where` (`.^all.grep`) and `.^update` (`.^all.map`) as Xliff has suggested

**Comment by FCO** [comment]
Create new alias, but with different names:
- `.^grep` for `.^all.grep`
- `.^map` for `.^all.map`

That way the user should not learn new names but only that one could use the `Seq`'s method's names directly as meta-method. but on that way, why only `grep` and `map` has the meta-method homonymous?

**Comment by FCO** [comment]
Do not add any alias and let it be the way it is.

**Comment by FCO** [comment]
If you have any other suggestion, please comment.
and add an 👍 on the option you prefer, please!

**Comment by Xliff** [comment]
I'm fine with 1 or 2. It's not that I don't agree with the way things are spec'd out, I would just like the option to remove the `.^all` from my code if it becomes repetitive.

**Comment by FCO** [comment]
if it becomes repetitive, you can always do something like:

```perl6
my @posts := Post.^all;
@posts.grep: *.published;
```

**Comment by Xliff** [comment]
That ceases to be a worthwhile solution when you are dealing with a lot of models.

**Comment by MattOates** [comment]
I think "where" is an especially bad idea as a name as it will give people too deep an assumption of what is happening wrt SQL. "filter" might be better. The update with the map I don't really like so much. But have the ^map and ^grep with an implicit ^all I think makes sense.

**Comment by MasterDuke17** [comment]
I'm torn about "where". On one hand it makes sense, but on the other MattOates raises a good point. So yeah, I think "^grep" is good, and a non-updating "^map".

**Comment by vrurg** [comment]
Take my third +1 for `^grep` and `^map`. _Entities should not be multiplied without necessity._ As these two are perhaps the most used ones, it would probably make sense to shortcut them.

**Comment by moritz** [comment]
For the record, sqlalchemy requires you to always call `.query` on a session or a model, which makes it easy to see where the rubber hits the database, so to speak. I kinda like that, so I'm voting against an alias for now.

If you do want to introduce an alias, please go with `^grep` instead of something cleverer.

**Comment by albertferrico** [comment]
> Create new alias, but with different names:
> 
> * `.^grep` for `.^all.grep`
> * `.^map` for `.^all.map`
> 
> That way the user should not learn new names but only that one could use the `Seq`'s method's names directly as meta-method. but on that way, why only `grep` and `map` has the meta-method homonymous?

I also think that you can create custom methods, supporting the native ones
for example with ^where, make sense to call it filter_by or something like that

**Comment by Scimon** [comment]
One of the things I like about Red is it feels like writing Raku not SQL. I think if we're going with aliases keeping them Rakuish (`.^map` and `^.grep`) goes with the feel of Red more.

**Comment by bazzaar** [comment]
Though the idea of simplifying the syntax, by adding convenience aliases, is possibly a good one, maybe it's a bit early in the development cycle of RED. The module is still in the midst of development, and there isn't much actual usage knowledge yet. Perhaps, it's better not to constrain the developer's thought process with this change. It could be something for the future? Also, I'm not sure that creating 'hybrid syntax' alias names is really the best plan. When querying a database, I'd rather use syntax that is consistent across the entire RED module, and I think we should wait for that to evolve.

**Comment by albertferrico** [comment]
> Though the idea of simplifying the syntax, by adding convenience aliases, is possibly a good one, maybe it's a bit early in the development cycle of RED. The module is still in the midst of development, and there isn't much actual usage knowledge yet. Perhaps, it's better not to constrain the developer's thought process with this change. It could be something for the future? Also, I'm not sure that creating 'hybrid syntax' alias names is really the best plan. When querying a database, I'd rather use syntax that is consistent across the entire RED module, and I think we should wait for that to evolve.

You made a good point, but I differ from you in one thing. If there are aliases, I think it would be better from a point of view of adoption. I'm very new to raku and if I see an alias rather than actual syntax, maybe I don't feel so frustrated when I try to use the module. I think allowing both (native syntax and aliases) is a good thing to spread the word and make it more user friendly. We need to think that not every developer has a lot of experience in raku, or even, it wouldn't be necessary. Just land on the module page, read a little the docs and start to play with it.

**Comment by FCO** [comment]
After 7 months, I think there is another option:

Creating a `is handling<map grep>` model’s trait. Using that, one could add `map` and/or `grep` that would be aliases to the ResultSeq’s originals. And maybe accept renaming like: `is handling(map => “update”, grep => “where”)` for the people who prefere other names.

Comments?

**Comment by FCO** [comment]
I've added that `is handling` trait as an experimental feature. https://github.com/FCO/Red/commit/c75e368aadf8f207ac5b5b81bb8b5cd0f10359f9
Please, comment

**Comment by vrurg** [comment]
Though I'm currently not using Red, but overall it sounds like a good compromise.
