### ISSUE TITLE
SQLite stores Bool as 1/0; Red does not inflate it again

### ISSUE THREAD

**Issue by Altreus** [FCO/Red#410]
Many databases store booleans as integers but I'm only testing with SQLite right now so I can't speak for others.

It seems like if I insert a new row with a boolean defined, the resulting object has a `0` instead of  `False`.

One would expect automatic inflation of typed columns.

In fact, would it make sense to have default inflation/deflation based on the type of the column? `:inflate( { $data-type.new($_) })`, and `:deflate( { ~$_ } );` or `+$_` depending on type.

```
use lib 'lib';
use Database;
use Red;

my $*RED-DB = database "SQLite", :database<./pg.db>;

my $t = Transaction.^create;

$t.say;
```

```
use Red;
use LibUUID;

model Transaction is table<transactions> {
    has UUID    $.id            is column{
        :id,
        :inflate( {UUID.new($_)} ),
        :deflate( {~$_})
    } = UUID.new;
    has Bool    $.closed        is column = False;
    has UUID    $.customer-id   is column{:nullable};
}
```

```
Transaction.new(id => UUID.new(bytes => Buf[uint8].new(227,255,141,213,49,32,72,53,140,163,221,32,81,173,234,82)), closed => 0, customer-id => Any)
```

**Comment by FCO** [comment]
Fixed with https://github.com/FCO/Red/commit/40255fd8e0cc212e9a4315b9fc5028ec5bda4baf

**Comment by FCO** [comment]
Thank you!
