### ISSUE TITLE
Failure on the latest rakudo master

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#422]
A recent change by lizmat introduced compile-time check of attribute value type. As a result, Red is broken. The problem source is in `MetamodelX::Red::OnDB` module, method `set_helper_attrs` where an attribute is declared as `Bool` gets assigned with a routine the very next line.

**Comment by vrurg** [comment]
**UPD** Not a `Red` bug. Initially I though a type mismatch slipped in somehow, but I was wrong.

Not closing until rakudo/rakudo#3449 or another fix is merged.

**Comment by lizmat** [comment]
Is there a way to reproduce this without needing Red ?

**Comment by vrurg** [comment]
@lizmat I better open an issue on rakudo and will post a golfed-down sample there.
