### ISSUE TITLE
Red install fails on Centos

### ISSUE THREAD

**Issue by melezhik** [FCO/Red#423]
Hi @FCO ! 

Installs fails with error

http://repo.westus.cloudapp.azure.com/sparky/report/centos/560

22:57:02 05/08/2020 [bash: zef install Red] ===> Testing: Red:ver<0.1.6>:auth<Fernando Correa de Oliveira>:api<2>
22:57:02 05/08/2020 [bash: zef install Red] [Red] Cannot modify an immutable TicketStatus (TicketStatus.new(id ...)
22:57:02 05/08/2020 [bash: zef install Red] [Red]   in block <unit> at t/05-ticket.t line 74
22:57:02 05/08/2020 [bash: zef install Red] [Red] Use of Nil in numeric context
22:57:02 05/08/2020 [bash: zef install Red] [Red]   in block  at /home/muaofjxykswbpgdvelcr/.zef/store/Red-0.1.6.tar.gz/Red-0.1.6/.precomp/9629F0299DBDE3D05F4BC2B06CBFE773375F07D6/F2/F2E53992C6FFEDC5DC3B09E6E9D69BBEB965D56B line 1
22:57:02 05/08/2020 [bash: zef install Red] ===> Testing [FAIL]: Red:ver<0.1.6>:auth<Fernando Correa de Oliveira>:api<2>

HTH

Alexey

**Comment by FCO** [comment]
@melezhik how can I test it?

**Comment by melezhik** [comment]
Hi! RakuDist has moved to http://rakudist.raku.org/ , I could rerun test here. Though there is no CentOS docker here yet ( I could add it later ).

**Comment by melezhik** [comment]
oh, I could see you've already run it.

**Comment by melezhik** [comment]
Unfortunately I have an issue with enabling CentOS on RakuDist due to CentOS 8 does not have `zstd` in repos, which makes it impossible to install Rakudo from whateverable, so you'd probably could close this issue now.

**Comment by FCO** [comment]
Sorry for the delay

**Comment by melezhik** [comment]
NP. I finally managed to bootstrap CentOS for RakuDist.
Red test on CentOS 8 passes now - http://rakudist.raku.org/sparky/report/centos/208
Tests on Alpine have an issue, but it is out of scope.

**Comment by FCO** [comment]
Please, would you mind to open a new issue with the alpine’s issue?
