### ISSUE TITLE
Add documentation on how to do a JOIN operation

### ISSUE THREAD

**Issue by samebchase** [FCO/Red#437]
Hi, I was able to read the tests and find out how to do a JOIN by calling the `^join` method.

Assume I have Table A with cols A1, A2 and Table B with cols B1, B2. Now, I do something like:

```raku
for A.^join(B, *.A1 == *.B1).^all.head(1) -> $row {
        say $row;
}
```
now, when I print `row`, I can see all the columns from B, but I cannot see any columns from A. How do I modify the select clause so that I can see columns from B as well?

In the generated SQL that is getting printed on the console, I see that all the columns form B are in the `SELECT`. I want to modify this to include a few columns from A as well.

**Comment by FCO** [comment]
Hi! Thanks for this issue!

For getting fields from A and B you could do something like this:

```raku
use Red:api<2>;

model A is table<AAA> {
   has $.id is serial;
   has $.A1 is column;
   has $.A2 is column;
}
model B is table<BBB> {
   has $.id is serial;
   has $.B1 is column;
   has $.B2 is column;
}

red-defaults "SQLite" ;

schema(A, B).create;

A.^create: :A1(^10 .pick), :A2(^10 .pick) for ^10;
B.^create: :B1(^10 .pick), :B2(^10 .pick) for ^10;

my $*RED-DEBUG = True;
say A.^join(B, *.A1 == *.B1).^all.map({ A.A1, A.A2, .B1, .B2 }).head 
```

But it will return as an array.

```
SQL : SELECT
   AAA.A1 as "data_1", AAA.A2 as "data_2", b_1.B1 as "data_3", b_1.B2 as "data_4"
FROM
   AAA
    INNER JOIN BBB as b_1 ON AAA.A1 = b_1.B1
LIMIT 1
BIND: []
(1 1 1 4)
```

there is another way of doing that would be:

```raku
say A.^all.join-model(B, *.A1 == *.B1).map({ A.A1, A.A2, .B1, .B2 }).head
```

And that way, it's easier to pre-filter A:

```raku
say A.^all.grep(*.A2 > 3).join-model(B, *.A1 == *.B1).map({ A.A1, A.A2, .B1, .B2 }).head
```

But `.^join` and `.join-model` are used to create custom joins.
Maybe the best way of doing that would be making it a relationship to-1.
Relationships to-1 are automatically pre-fetched. So, you could do something like:

```raku
use Red:api<2>;

model A is table<AAA> {
   has $.id is serial;
   has $.A1 is referencing(*.B1, :model<B>);
   has $.b is relationship(*.A1, :model<B>);
   has $.A2 is column;
}
model B is table<BBB> {
   has $.id is serial;
   has $.B1 is column;
   has $.B2 is column;
}

red-defaults "SQLite" ;

schema(A, B).create;

A.^create: :A1(^10 .pick), :A2(^10 .pick) for ^10;
B.^create: :B1(^10 .pick), :B2(^10 .pick) for ^10;

my $*RED-DEBUG = True;
my $a = A.^all.head;
say $a;
say $a.b
```

the would run:

```
SQL : SELECT
   AAA.id , AAA.A1 , AAA.A2 , a_a_a_b.id as "AAA_b.id", a_a_a_b.B1 as "AAA_b.B1", a_a_a_b.B2 as "AAA_b.B2"
FROM
   AAA
    LEFT JOIN BBB as a_a_a_b ON AAA.A1 = a_a_a_b.B1
LIMIT 1
BIND: []
A.new(id => 1, A1 => "7", A2 => "0")
B.new(id => 10, B1 => "7", B2 => "1")
```

**Comment by FCO** [comment]
https://github.com/FCO/Red/blob/master/docs/tutorials/cookbook.md#custom-join

**Comment by samebchase** [comment]
Hey @FCO,
This comprehensively answers my question that I got stuck on yesterday, and I hope it serves as a useful reference for anyone else running into the same question.
Will let you know as I use the library more.
Have a great day. 😎

**Comment by FCO** [comment]
There is a new entry on cookbook to custom join: https://github.com/FCO/Red/blob/master/docs/tutorials/cookbook.md#source-and-source-id

**Comment by samebchase** [comment]
I tried it out, and it worked correctly.

Hey, thanks for the above information, I was able to move further a little, but unfortunately I have hit another wall.

What's the best way to compose joins together?

i.e. if I have relation A with columns X1,Y1,Z1 which are all ids that need to be joined to three other relations X, Y and Z so that I have one compound relation what's the best way of going about that?

I need A to be joined with three other relations. I tried doing something like;

```raku
my $x-a = X.^join(A, *.id == *.X1);
my $y-x-a = Y.^join($x-a, *.id == *.Y1);
my $z-y-x-a = Z.^join($y-x-a, *.id == *.Z1);

# Now I want to be able to do a `.map` and pick out columns from all four of the relations which I hope are joined correctly by now.
```
 At this point I would imagine `$z-y-x-a` to be the compound relation `A` joined with `X`,`Y`,`Z` using the columns `X1`,`Y1` and `Z1`.

Also tried using the feed operator, but that didn't work with the `.^join` method. 

I am planning to use the prefetching feature using `is relationship`, but I want to make sure I understand how to do more complicated custom joins first, so that I don't get stuck later when I do need to be able to join.

**Comment by FCO** [comment]
I've never tried anything like that. But why aren't you using relationships for that? If X has a relationship to Y and Y has a relationship to Z, just fetching X you would get all 3. (if those were to-1 relationships)

I'll take a look after day-job

**Comment by samebchase** [comment]
Hey @FCO, thanks so much for the quick response, 🙏

Think of A as the base relation, and it needs some extra stuff from `X`,`Y` and `Z`. So in a sense I need to join `A-X`, `A-Y` and `A-Z`, so that the final franken-relation will have _everything_ from `A`, `X`, `Y` and `Z`.

I will try with relationships after I am done with $DAYJOB work. That might be more convenient.

**Comment by samebchase** [comment]
Using relationships worked beautifully, thank you.
