### ISSUE TITLE
Specify table name convention on model creation

### ISSUE THREAD

**Issue by kawaii** [FCO/Red#439]
When creating tables, `Red` generally does a good job with the naming convention, defaulting to using `_` in the case of `has Int $.user-id is id;` for example. _Some_ database systems allow for the use of `-` in their column names however, and `Red` provides no way to specify an override for the column name if you'd like to change this.

I suggest we allow a parameter to be set, allowing the user to specify their own column name on creation.

**Comment by FCO** [comment]
Now that's possible doing something like this: https://github.com/FCO/Red/blob/master/t/48-experimental-formater.t
