### ISSUE TITLE
Add `:has-one` to `is relationship`

### ISSUE THREAD

**Issue by FCO** [FCO/Red#452]
Currently, there is no way of doing a one-to-one relationship, only one-to-many is doable, where:

```raku
has @.rel is relationship(*.fk, :model<remote>)
```

will use remote's `.fk` to do the relationship, (becoming a has-many)
and

```raku
has $.rel is relationship(*.fk, :model<remote>)
```

(the difference is the sigil `$` or `@`)
will use local's `.fk` to do the relationship (becoming a belongs-to)

if I want to do a one-to-one (a has-one and a belongs-to), currently I need to do a has-many and create a method to return it's `.head`. Not a good solution and it loses a lot of features from the relationship.

My suggestion is to make it something like this:

```raku
has $.rel is relationship(*.fk, :model<remote>, :has-one)
```

that will search the `.fk` on the remote model but won't return a ResultSeq, it will return only 1 result.

A question is, should we prefetch it as we do with belongs-to?

**Comment by Altreus** [comment]
I think prefetch should be a property of using the relationship, not defining it. What data you're about to use depends on what you're about to do, so whether or not you prefetch (potentially through multiple tables) is in the hands of the user.

**Comment by FCO** [comment]
@Altreus I totally agree but I couldn't find a good syntax for defining it on "query-time".

**Comment by FCO** [comment]
maybe something like (using the example):

```raku
local.^all(:prefetching<rel>)
```

but I'm not sure if I like it

**Comment by FCO** [comment]
I've created a new experimental feature called `has-on`, and now this works:

```raku
use Red <has-one>;

model Bla {
   has $!id is serial;
   has $.name is column;
   has $!ble-id is referencing(*.id, :model<Ble>);
   has $.ble is relationship(*.ble-id, :model<Ble>);
}

model Ble {
   has $!id is serial;
   has $.name is column;
   has $.bla is relationship(*.ble-id, :model<Bla>, :has-one);
}

red-defaults "SQLite";

schema(Bla, Ble).create;

Bla.^create: :name<bla1>, :ble{ :name<ble1> };

say Bla.^all.head.ble
```

and prints:

```raku
Ble.new(name => "ble1")
```
