### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by melezhik** [FCO/Red#455]
Hi @FCO! I run this example from Red's doc an get an error:

http://rakudist.raku.org/sparky/report/RakuPlay-3/1373

```
[31m===[0mSORRY![31m===[0m Error while compiling /home/rkp-3-89e12a98/code.rakuplay-1605825142.raku
On Red:api<2> ":model" is required on "is referencing"
at /home/rkp-3-89e12a98/code.rakuplay-1605825142.raku:7
```

HTH

Alexey

**Comment by FCO** [comment]
Thanks, I'll fix that.

**Comment by melezhik** [comment]
yeah, you can always run code samples to check your doc/code in RakuPlay - https://sparrowdo.wordpress.com/2020/11/19/rakuplay-introduction/

**Comment by FCO** [comment]
It seems to be fixed now (https://rakudist.raku.org/sparky/project/RakuPlay-2)
Thank you very much!

**Comment by melezhik** [comment]
cool. the correct link is that - https://rakudist.raku.org/sparky/report/RakuPlay-2/1402 😄

**Comment by FCO** [comment]
Thanks again!
