### ISSUE TITLE
SQL generated with untranslated column name

### ISSUE THREAD

**Issue by japhb** [FCO/Red#461]
Given the table:

```raku
model Character is table<mugs_characters> does MUGS::Character is export {
    has Int $.id          is id;
    has Int $.persona-id  is referencing{  :column<id>,  model-ref('Persona') };
    has Str $.screen-name is column{ :unique };
    has     $.persona     is relationship( *.persona-id, model-ref('Persona') );
}
```

which Red created in the SQLite database as:

```sql
CREATE TABLE mugs_characters(
   id integer NOT NULL primary key ,
   persona_id integer NULL references mugs_personas(id),
   screen_name varchar(255) NOT NULL ,
   UNIQUE (screen_name),
   UNIQUE (screen_name)
);
```

Red responds to this code looking up character screen names for a given persona:

```raku
my @characters = .characters.map(*.screen-name);
```

with:

```sql
SQL : SELECT
   mugs_characters.screen-name as "data_1"
FROM
   mugs_characters
WHERE
   mugs_characters.persona_id = ?
```

but that fails because `mugs_characters.screen-name` has a hyphen in it instead of an underscore.  Most other queries have been generated with something more like `mugs_characters.screen_name as "mugs_characters.screen-name"`, which correctly translates the column name to be SQL-safe.

(That's the primary bug I'm reporting here; note there's another bug in the above which is that Red generates an extra copy of the `UNIQUE(screen_name)` constraint when creating the table for some reason.)

**Comment by FCO** [comment]
Thank you very much for your report! I'll take a look at that ASAP. (Sorry for the delay on the response)

**Comment by FCO** [comment]
Hi, @japhb! Would you mind to tell me your Red's version? I thought I've already fixed that double unique issue.

**Comment by japhb** [comment]
Hmmm, looks like I'm slightly behind (0.1.26 instead of 0.1.29):

```$ zef info Red
- Info for: Red
- Identity: Red:ver<0.1.29>:auth<Fernando Correa de Oliveira>:api<2>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: Yes, as Red:ver<0.1.26>:auth<Fernando Correa de Oliveira>:api<2>
Description:	 A Raku ORM
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/F/FC/FCO/Perl6/Red-0.1.29.tar.gz
Provides: 101 modules
Depends: 4 items
```

Ah, I see I was still building from my local tree from when I sent the PR last fall, and hadn't merged your updates.  Fixing that and rebuilding.

**Comment by FCO** [comment]
Please, let me know if that fixed both iasues

**Comment by FCO** [comment]
I've done a small test here, it seems to be working:

```
raku -I. -MRed -e '
model Persona {}

model Character is table<mugs_characters> {
    has Int $.id          is id;
    has Int $.persona-id  is referencing{  :column<id>,  :model<Persona> }; 
    has Str $.screen-name is column{ :unique };
    has     $.persona     is relationship( *.persona-id, :model<Persona> ); 
}
my $*RED-DEBUG = True;

red-defaults "SQLite";
Character.^create-table;


.say for Character.^all.map: *.screen-name
'
SQL : CREATE TABLE mugs_characters(
   id integer NOT NULL primary key ,
   persona_id integer NULL ,
   screen_name varchar(255) NOT NULL ,
   UNIQUE (screen_name)
)
BIND: []
SQL : SELECT
   mugs_characters.screen_name as "data_1"
FROM
   mugs_characters
BIND: []
```

**Comment by japhb** [comment]
Looks like both bugs were indeed fixed in the latest version.  Thanks for taking a look, and sorry to waste your time!
