### ISSUE TITLE
Could not find relationship model when model files are deep in a file structure

### ISSUE THREAD

**Issue by vtdevpm** [FCO/Red#462]
When I test the [example blog2 ](https://github.com/FCO/Red/tree/master/examples/blog2)in the following configuration:
./lib/Database/Person.rakumod
./lib/Database/Post.rakumod
./index.raku

I adjust index.raku with the proper paths:
```
use lib <lib>;
use Database::Person;
use Database::Post;
```

But I get an Error when it tries to create a Post table: "**Could not find Person in:** [list of my raku bin lib]"

If instead of putting the models inside the Database folder, I simply put them under lib:
./lib/Person.rakumod
./lib/Post.rakumod
./index.raku

with index.raku:
```
use lib <lib>;
use Person;
use Post;
```

Then it works.

**Comment by khalidelboray** [comment]
Did you rename the classes to Database::Person and Database::Post ?
If you didn't, i think this triggered the issue here.

**Comment by vtdevpm** [comment]
I don't think it is the issue.
1- in my example, the Person table is created. Only the Post table that prefetchs $.author has an error.
2- the name of the models are used to name the tables. Turns out Database::Person is an invalid table name...

**Comment by vrurg** [comment]
You can use `is table` trait on a model to bind it to a specific table. Otherwise, if I'm not mistaken, `Red` transforms `::` into `_`. `Database::Person` should by default map into `database_person`.

**Comment by FCO** [comment]
Exactly, Red, by default, do that, but you can use `is table` to set the tables name to whatever you want. There are also 2 experimental features that allows you to change that behaviour, the `formaters` one  and the `shortname` one (https://fco.github.io/Red/tutorials/experimental.html).

**Comment by jonathanstowe** [comment]
I think this is the same as #81

**Comment by vtdevpm** [comment]
Thank you.

So the solution is:
1- rename the models `Person` and `Post` to `Database::Person`, `Database::Post` to respect the file structure
2- use the trait `is table` to avoid the issue #81

**Comment by jonathanstowe** [comment]
Or use the experimental `formaters` feature and supply a sub in `&*RED-TABLE-FORMATER` that will convert the model class name to a format of name that you want to use.

**Comment by FCO** [comment]
or use the experimental `shortname` that will use the shortname of the model as the table name.
