### ISSUE TITLE
Any way to update an existing model instance from DB? 

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#463]
Is there a way to update a model instance from a DB if the record in the DB was changed? Something like `$model.refresh`? Or even `$model.refresh('attribute_name')`?

**Comment by FCO** [comment]
No, there is nothing like that currently. That may be a good idea (but as a metamethod (.^refresh)). While we do not implement something for that, maybe something like this could me used:

```raku
$model = $model.^rs.head; # not tested code
```

**Comment by vrurg** [comment]
I meant `refresh` to be a metamethod, actually. Anyway, `$model = ` is not what I need. My actual need is due to me attempting to implement JSON-RPC over WebSocket (done, actually) with authorization/authentication. My auth API is implemented by a session model. It's a multi-role object which also does `Cro::HTTP::Auth` and `Cro::RPC::JSON::Auth`. It updates `user_id` column upon login and `expires` column upon logout.

WebSocket is the tricky part here. It gets authorized once, when HTTP `GET` is converted into socket. Then it exists until closed. If session gets updated outside of the socket managing code then it wouldn't know about it.

The other problem with this setup is when a user opens two pages in the same browser. In this case I get two `Cro` pipelines on the server, both referring to the same session record in database. It would be even worse when each pipeline is opened on its own server.

The solution is to update the session data from inside the session model before each JSON-RPC call. Then the authorization code can check the session is still valid. But currently to do so I would either use SQL directly; or re-fetch the session object on each call (slow).

But as an alternative it could be done with the parameterized version of `refresh`: `self.^refresh('expires')` – and it would only update one attribute, resulting in very simple SQL and very short response, minimizing the performance impact.

**Comment by FCO** [comment]
I think that’s a easy thing to be done, I’ll implement that as soon as possible.

**Comment by FCO** [comment]
@vrurg I've done a new experimental feature called `refreshable`. That  adds a `.^refresh` meta-method on defined model. It accepts a list of columns names or nothing at all, and "refreshes" those columns (ar all columns if no list was defined) with the actual data from the database.

**Comment by vrurg** [comment]
@FCO Though I wrote it on IRC, but anyway: thanks again for so fast response!

That's all good news I have. Then bad news come. It doesn't work for pre-compiled models. Or, at least, it looks like pre-compilation of more than one model results in an STable conflict. It's not clear to me what why exactly it happens, but most likely it's caused by adding a role. As a result we get a new copy of `Model` per each `use`.

I'm trying to find a solution, but without much luck so far.

Meanwhile, the investigation brought up a weird result. I tried to conditionally apply `Refreshable` role in `MetamodelX::Red::Model` `compose` method. While doing so I made a mistake and to locate it I added a debug print. It came up with something like:

```
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
--- ADDING MetamodelX::Red::Refreshable to user_sessions_user
[... and tens more lines of the kind...]
```

Backtracing reported that all prints are result of `MetamodelX::Red::Model::alias` method invocation. While the repetition itself is a result of my code (I'm trying to benchmark and do 100 calls to `.^load` in a row), but to my opinion all but the first call are excessive here and could be optimized away by keeping a cache of aliases.

**Comment by FCO** [comment]
Thanks for your message! Sorry for not making it work. Is there any code you could share to let me try to fix it? I'll try to fix that ASAP.
Thanks

**Comment by vrurg** [comment]
So far, I'm afraid, there is no good fix for as long as `MetamodelX::Red::Model` is used in `EXPORTHOW::DECLARE`. For now I think this is what causing the `STable` conflict error message because Rakudo tries to merge `Red::EXPORTHOW::DECLARE` with two different `model` symbols in them. BTW, same problem is with `migrations` and `supply` – they use the same approach.

The really good fix would use a slang. In this case you could dynamically check what experimentals are in effect and modify the class you use for `model` on the fly. But considering that RakuAST + macros are to come as soon as before the end of this year I don't think it's a good way to go.

So, I rather inclined towards `MetamodelX::Red::Model` consuming all the experimental roles anyway. And then somehow to block the methods they provide.

Though I'll try a one or two more tricks, but don't expect them to work.

**Comment by FCO** [comment]
I'll try some changes as well as soon as I can

**Comment by vrurg** [comment]
Not sure how will my day go, so wanna share an idea I have.

I tried implementing a slang yesterday. There is a weird problem with Rakudo which doesn't let me do it: to implement meta-ops Rakudo mixins `Oper` roles into the grammar and it overrides any slang installed! Dunno if I be able to get it fixed. So, let's say slang doesn't work for us here.

Another idea came to me too late to try it. But it's rather simple in nature: you can dynamically mixin necessary roles into `MetamodelX::Red::Model` inside its `compose` and use the result for creating a new model type. It would only require replacing `self` with another symbol bound to the resulting HOW.

As a side note: `mixin` parameterizes based on role list and tries to cache the result. For this reason it's important to always use the same order of experimental roles.

**Comment by FCO** [comment]
Thanks, I'll give it a try.

**Comment by FCO** [comment]
@vrurg I've tried to do that with mixin on compose. It seems to work with pre-compilation, but it's breaking anything with using relationship. https://github.com/FCO/Red/commit/41e0dfdda59742aac3139858872f78e154d278e3
I'll continue trying tomorrow, but if someone could help me to find the problem, it would help a lot.

**Comment by vrurg** [comment]
I was totally wrong about `compose`. See #465 for the correct approach where `HOW` gets mixins before it's instantiated.

**Comment by vrurg** [comment]
Meanwhile, I have played with the PR. Unfortunately, I see no positive performance outcome of refreshing just one attribute comparing to complete fetch of a record. Haven't done debugging yet, though, as the patch was done just a couple of minutes ago.

In either case, the ability to update a record from within itself is useful feature on its own. I missed it as such.

**Comment by vrurg** [comment]
My bad, copy/paste error resulted in incorrect benchmark. So, tested with a simple session record of columns stringy `id`, integer `user-id`, and integer `expires`. Refreshing of single `expires` column is about 1.7 times faster, then re-fetching the whole record with `.^load`.

**Comment by FCO** [comment]
Great! And thank you very much for all the help!!!

**Comment by vrurg** [comment]
I have a funny update in #466.

**Comment by vrurg** [comment]
There is a bug with parameter-less `.^refresh`: it resets `expires` column to `Any` for me. Perhaps it's a one-off problem as the column is the last attribute of model. When moved one position up in the list of attribute declarations things work as expected. Same time, `user-id` which is a `referencing` column, is not affected neither when it's second last, nor when it's the last one.

And thank you!

**Comment by FCO** [comment]
Is expired populated on DB?

**Comment by vrurg** [comment]
Sure, it is.

**Comment by FCO** [comment]
Could you share part of the code to let me try to fix it tomorrow, please?

**Comment by vrurg** [comment]
I barely have time to make something runnable on its own. But hopefully the provided snippets would serve well enough.

```raku
model DB::Session is table<user_sessions> is nullable {
    also does Cro::HTTP::Auth;

    has Str $.id is id;
    has UInt $.user-id is referencing( *.id, :model<DB::User> ) is rw;
    has UInt $.expires is column is rw;
    has $.user is relationship( *.user-id, :model<DB::User> ) is rw; # I think this line can be just thrown away.
}
```

I provide the entire benchmark script. So, perhaps you would manage to find out why refreshing is currently slower than `.^load`.

```raku
use lib 'lib';
use Red:api<2>;
use DB::Session;

red-defaults "Pg", ...;

constant COUNT = 100;

my $base-st = now;
for ^COUNT {
    my $s = 0;
}
my $loop-time = now - $base-st;
note "LOOP TAKES: ", $loop-time;

note "... start";
my $full-st = now;
for ^COUNT {
    my $s = DB::Session.^load: :id<Bxy7PubIblYyDmSTEXsEy6QsBnpEInQkhb9ylccrw8WOcoAkfZXYELRzW1oArWf1>;
}
my $full-et = now;

note "FULL: ", $full-et - $full-st - $loop-time;

my $s = DB::Session.^load: :id<Bxy7PubIblYyDmSTEXsEy6QsBnpEInQkhb9ylccrw8WOcoAkfZXYELRzW1oArWf1>;
note $s;
my $refr-st = now;
for ^COUNT {
    $s.^refresh;
}
my $refr-et = now;

note "REFRESH: ", $refr-et - $refr-st - $loop-time;

note $s; # At this point `expires` is `Any` unless the `.^refresh` above is invoked with 'expires' argument
```

**Comment by vrurg** [comment]
A note on performance. All this time I was running it on Rakudo HEAD. The latest update broke Red up to the level of moar SIGSEGV'ing when trying to run some tests. So, I switched to 2020.12 release. This has magically fixed the performance! Refresh is now ~1.3 times faster than full load.

**Comment by FCO** [comment]
thanks for letting me know! But `expires` is still becoming `Any`, right?

**Comment by FCO** [comment]
it should be fixed, could you retry, please?

**Comment by vrurg** [comment]
Fixed, thank you! I think the issue can be closed now.
