### ISSUE TITLE
Slight amendment to `&*RED-TABLE-FORMATER`?

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#464]
Hi,
for the `&*RED-TABLE-FORMATER` `formaters` feature it might be nice to have the option to supply either the `Red::Driver` or something else that can determine the DB in play to the formatting sub so that DB specific rules can be applied (for instance introducing a namespace or schema qualification to the table name.)

The thing that calls the sub can do a check on the signature before  using whichever calling convention matches.

**Comment by FCO** [comment]
that's a great idea! maybe for the table- and for the column-formater.
Thanks!

**Comment by jonathanstowe** [comment]
I'm guessing it would even be possible to pass a multi with each DB type catered for per candidate if one wanted to support multiple different databases with different rules nicely.

**Comment by FCO** [comment]
I'm now thinking if it would make sense to have the formatter method on Red::Driver (each driver could have its own table name formatter) and it could be overridden on each driver. Or have something like:

```raku
Red.table-formatter: -> $table, :$db where "SQLite" { ... }
Red.table-formatter: -> $table, :$db where "Pg" { ... }
```

and it could return a string (used as the table name) or a Pair, where the key would be the schema and the value the table name (or maybe a Red::SchemaTable object)

@jonathanstowe what do you think about that?

**Comment by jonathanstowe** [comment]
Sounds good to me. :+1:

**Comment by FCO** [comment]
first step: https://github.com/FCO/Red/commit/55e737da030e9c71dacc47f2de874a7025ed37f9 https://github.com/FCO/Red/commit/9da5a98b8f72683ae76ccf1821666856ca7ba5c7

**Comment by FCO** [comment]
I'm rethinking it... maybe we could just add the `table-formatter` on each driver, and one could change the formatter with something like:

```raku
red-do SQLite => { .table-formatter: { ... } }, Pg => { .table-formatter: { ... } }
```

or even accept it as parameter on [database](https://fco.github.io/Red/api/Red/Database)
