### ISSUE TITLE
Red model from DBIx::Class schema

### ISSUE THREAD

**Issue by rfilipo** [FCO/Red#469]
There is an easy way to generate a Red model from some regular DBIx::Class schema? It could be a great improvement as many Perl apps use DBIx::Class. It could facilitate converting old apps from Perl 5 to Raku, for example.

**Comment by jonathanstowe** [comment]
I've got one knocking around somewhere that I've used for a project of my own.  Let me clean it up a bit and I'll post it up somewhere.

**Comment by FCO** [comment]
Thank you @jonathanstowe, I’m looking forward to see that! :)
And thank you for the great idea @rfilipo ! :) I’m glad you are interested on Red! :)

**Comment by jonathanstowe** [comment]
There you go https://github.com/jonathanstowe/dbic-to-red - it works but it can probably be improved upon.
