### ISSUE TITLE
Schema doesn't create uniques with Pg

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#473]
Taken these three models and using `schema` to create actual tables and there will be no `unique` defined for any of tables in the postgresql DB:

```raku
model Foo::Bar is table<bar> {
    has $.id is serial;
    has Str $.v1 is column{ :!nullable, :unique<u1> };
    has Bool $.v2 is column{ :!nullable, :unique<u1> };
}
model Foo::Baz is table<baz> {
    has $.id is serial;
}
model Foo::B2B is table<bar2baz> {
    has UInt $.bar-id is column{ :id, :references(*.id), :model-name<Foo::Bar>, :unique<bb> };
    has UInt $.baz-id is column{ :id, :references(*.id), :model-name<Foo::Baz>, :unique<bb> };
}
schema(Foo::Bar, Foo::Baz, Foo::B2B).create;
```

Produced SQL statements:

```
SQL : CREATE TABLE bar2baz(
   bar_id integer NOT NULL,
   baz_id integer NOT NULL
)
BIND: []
SQL : CREATE TABLE baz(
   id integer NOT NULL primary key
)
BIND: []
SQL : CREATE TABLE bar(
   id integer NOT NULL primary key,
   v1 varchar(255) NOT NULL ,
   v2 boolean NOT NULL
)
BIND: []
SQL : ALTER TABLE bar2baz
        ADD CONSTRAINT bar2baz_bar_id_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES bar(id)
BIND: []
SQL : ALTER TABLE bar2baz
        ADD CONSTRAINT bar2baz_baz_id_baz_id_fkey FOREIGN KEY (baz_id) REFERENCES baz(id)
BIND: []
```

This works as expected for `SQLite`, though:

```
SQL : CREATE TABLE bar2baz(
   bar_id integer NOT NULL references bar(id),
   baz_id integer NOT NULL references baz(id),
   UNIQUE (bar_id, baz_id),
   PRIMARY KEY (bar_id, baz_id)
)
BIND: []
SQL : CREATE TABLE baz(
   id integer NOT NULL primary key AUTOINCREMENT
)
BIND: []
SQL : CREATE TABLE bar(
   id integer NOT NULL primary key AUTOINCREMENT,
   v1 varchar(255) NOT NULL ,
   v2 integer NOT NULL ,
   UNIQUE (v1, v2)
)
BIND: []
SQL : COMMIT
BIND: []
```

Same applies to primary key declaration, BTW. It's not as apparent as for uniques, but I had related questions until mentioned the `PRIMARY KEY` statement in `bar2baz` declaration. So, no more questions but a statement of fact now. :)

**Comment by FCO** [comment]
The problem seems to be [here](https://github.com/FCO/Red/blob/master/lib/Red/Driver/CommonSQL.pm6#L174), we are not adding any kind of constraint here other than FK.

**Comment by FCO** [comment]
@vrurg could you please confirm if that's working for you? Thanks!

**Comment by FCO** [comment]
@vrurg any news about this?

**Comment by vrurg** [comment]
Oh, my... I haven't even replied to your previous request! Sorry for that.

No, I had to put aside that project for indefinite period of time. Still hope to sort numerous issues out and get back to it before June.

**Comment by FCO** [comment]
Thanks for your reply! Would you mind if I close this issue and if you find that's not working you reopen it?
