### ISSUE TITLE
ResultSeq `create-comment-to-caller` method can result in a warning

### ISSUE THREAD

**Issue by vrurg** [FCO/Red#474]
The cause is a line like the following one in a test suite:

```raku
is Model.^all.elems, $expected, "a message";
```

It results in:

```
Use of uninitialized value of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub comment-sql at /home/vrurg/src/Raku/BOTradingWeb/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 79
  in method create-comment-to-caller at /home/vrurg/src/Raku/BOTradingWeb/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 69
  in method elems at /home/vrurg/src/Raku/BOTradingWeb/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 344
  in block <unit> at t/db/010-account.rakutest line 21
```

I managed to track it down to the following line in ResultSeq.pm6:

```raku
    given Backtrace.new.tail(*-3).first: {
```

Backtrace at the moment of warning consists of exactly three frames:

```
          in method create-comment-to-caller at /home/vrurg/src/Raku/BOTradingWeb/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq)>
          in method elems at /home/vrurg/src/Raku/BOTradingWeb/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 344
          in block <unit> at t/db/010-account.rakutest line 21
```

This causing `.tail(*-3)` to result in `Nil` and `%data` is consequently filled with `Any` values.

What is really confusing me is that the bug is a flapper. Though after adding some debug printing into the `create-comment-to-caller` method I seemingly got 100% reproducible results.

I played with using `*-2` as `tail` argument and it clearly prevents the warning, but I'm not sure if this will produce correct results for other call paths.
What is strange q

**Comment by FCO** [comment]
Thanks! I'll take a look as soon as possible

**Comment by FCO** [comment]
I've been trying to reproduce this with no luck. Could you share some code to let me reproduce it, please?

**Comment by vrurg** [comment]
Just've stumbled upon this issue. Perhaps, it's better to close it for now. Not sure if I myself would be able to reproduce the problem any time soon.
