### ISSUE TITLE
Problems with runtime application of roles to row objects.

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#478]
In [Tinky::DB](https://github.com/jonathanstowe/Tinky-DB) the `apply-workflow` method that comes from the `Tinky::DB::Object` role (which in turn gets it from `Tinky::Object` ) applies a further role at runtime which is generated based on the configuration of the workflow.  This works fine if the class doing the Tinky::DB::Object is a _normal_ class, but really comes off the rails if it is a Red model.  On further examination this applies to any role applied to any row object at run time:

Using `does` the role won't even apply, apparently blowing up somewhere in the `compose`:

```
use Red;

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

role Foo {
    method zub() {
    }
}


model Bar {
    has Int $.id is serial;
}

Bar.^create-table;

my $bar = Bar.^create;

say $bar.id;

$bar does Foo;

say $bar.id;
```
Results in:

```
1
No such method 'set_value' for invocant of type 'Any'
  in method <anon> at /home/jonathan/.raku/sources/96D8F39837748419EB797C2F28638CE9D509830D (MetamodelX::Red::Dirtable) line 140
  in block <unit> at tt line 22
```

If instead one uses `^mixin` it applies fine but the accessors for the columns get messed up:

```
use Red;

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

role Foo {
    method zub() {
    }
}


model Bar {
    has Int $.id is serial;
}

Bar.^create-table;

my $bar = Bar.^create;

say $bar.id;

$bar.^mixin(Foo);

say $bar ~~ Foo;

say $bar.id;
```
Which results in:

```
1
True
Ambiguous call to 'id(Bar+{Foo}: )'; these signatures all match:
  (Red::Model:D: *%_)
  (Red::Model:D: *%_)
  in block <unit> at tt line 26
```

It would seem that in both cases the `compose`  of `MetamodelX::Red::Model` is being called on the application of the role and doing something that it doesn't need to.

**Comment by jonathanstowe** [comment]
I _think_ that it may be because the `TWEAK` is getting wrapped multiple times in the `compose-dirtable`  just testing.

**Comment by jonathanstowe** [comment]
Okay, testing whether the wrapping has occurred previously (by applying a role to the `TWEAK` when it is wrapped,) results in both cases giving the same `Ambiguous call` exception, which is progress of sorts,

**Comment by jonathanstowe** [comment]
Narrowed down to `compose-columns` unconditionally adding the multi for the accessors, seems eminently fixable.

**Comment by jonathanstowe** [comment]
Nearly there with checking for the presence of the accessor before creating it, because they are created as `multi` it doesn't blow up if there is an existing method of the same name, I may refine the test to allow methods with the same name but a different signature.

Now to discover why the `col-data-attr` is winding up undefined in some circumstances.

**Comment by FCO** [comment]
Sorry, I've just seen that now! Trying to understand...

**Comment by jonathanstowe** [comment]
I've nailed this last bit down, it seems that somehow when the model is being recomposed during the role application the `$!col-data-attr` is not set *but* the `%!___COLUMNS_DATA___` does exist, possibly due to the order in which the attributes are added back or something.  So I think re-jigging the `set-helper-attrs` so that it looks up the `%!___COLUMNS_DATA___`  and, if it exists and `$!col-data-attr` is not set, set `$!col-data-attr` otherwise create the attribute as currently.

**Comment by jonathanstowe** [comment]
Oh not quite, in the `does` case the `TWEAK` gets called an additional time which causes the column values to be lost.

**Comment by jonathanstowe** [comment]
.... which is because the content of the already existing and populated `%!___COLUMNS_DATA___ ` is being overwritten by an empty one.

**Comment by jonathanstowe** [comment]
There.

**Comment by jonathanstowe** [comment]
FWIW I only discovered this because I fixed a problem in Tinky whereby the role that is created to reflect then transitions in the workflow was failing to be applied under some circumstances (and papered over with a `try`.)
