### ISSUE TITLE
Provide for `date(timestamp_column) = '2021-06-28'` 

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#485]
I find myself using this pattern quite often and it's quite difficult to implement with what there is right now.

I see it being implemented in two ways: firstly as an explicit `.date` column method on `DateTime` typed columns much the same as e.g. `.day` so it can be used in comparisons with a `Str` for instance,  and also a new candidate for the `eq` (or `==`,) operator where the LHS is a `Red::Column` with a type of `DateTime and presumably under the hood applies the first under the hood.

I can see where it needs to go, though I may not get to making a PR right away.

**Comment by FCO** [comment]
I'll try to take a look at it as soon as possible! (Sorry for not seeing this before)

**Comment by FCO** [comment]
Yes, I think we can do something like the [.day() method](https://github.com/FCO/Red/blob/master/lib/Red/ColumnMethods.pm6#L61)

**Comment by jonathanstowe** [comment]
The PR'd implementation would probably be enough for me to be honest.

**Comment by FCO** [comment]
I've just have done this:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/99834/124018025-52803380-d9df-11eb-878a-662702350638.png">

**Comment by FCO** [comment]
I've asked, on your PR, to rename that to `.yyyy-mm-aa()` what do you think?
