### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by sylints** [FCO/Red#49]
I'm a Perl 6 novice that would like to help where able.  What are the installation instructions to get started?

**Comment by FCO** [comment]
Thanks for the help!
Please tell me if that’s enough!

**Comment by sylints** [comment]
Thanks for the updated instructions!

I'm running a relatively fresh install of Ubuntu 18.04.  Looks like I need to get some other stuff installed too. Here is what I get when I currently attempt to install dependencies. 

![image](https://user-images.githubusercontent.com/11053903/46544011-a89c0880-c87f-11e8-909e-cd41be356c11.png)

**Comment by FCO** [comment]
Yes, those are DBIish dependencies... I’m not on my computer now test it out (sorry). What’s your Rakudo version? Have you tried to run `zef install DBIish`?

**Comment by sylints** [comment]
Running rakudo version 2018.08 built on MoarVM version 2018.08.

I zef installed DBIsh.

Here is what I see now when attempting to install dependencies:
![image](https://user-images.githubusercontent.com/11053903/46545020-6cb67280-c882-11e8-8fa2-9ad4dd43492f.png)

**Comment by FCO** [comment]
uuid-dev?

**Comment by sylints** [comment]
Yep!  I was able to install the dependencies, and the tests are all passing.  Thanks for the help!
