### ISSUE TITLE
SELECTing enums generates broken WHERE in most cases

### ISSUE THREAD

**Issue by patrickbkr** [FCO/Red#495]
```
use Red:api<2> <refreshable>;

red-defaults("SQLite");
my $*RED-DEBUG = True;

enum E <a b c>;
    
model M is rw {       
    has UInt $.id is serial;
    has E    $.my-e is column;
}
schema(M).create;
M.^create(my-e => a);

for M.^all.grep(*.my-e == a) { say $_.my-e; }
for M.^all.grep(*.my-e === a) { say $_.my-e; }
for M.^all.grep(*.my-e ⊂ (a)) { say $_.my-e; }
for M.^all.grep(*.my-e ⊂ (a, b)) { say $_.my-e; }
```

Outputs:

```
SQL : BEGIN
BIND: []
SQL : CREATE TABLE "m" (
   id integer NOT NULL primary key AUTOINCREMENT,
   my_e integer NOT NULL 
)
BIND: []
SQL : COMMIT
BIND: []
SQL : INSERT INTO "m"(
   my_e
)
VALUES(
   ?
)
BIND: [E::a]
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   _rowid_ = last_insert_rowid()
LIMIT 1
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   "m".my_e = 'a'
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   0
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   0
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   "m".my_e IN ( ?, ? )
BIND: [E::a, E::b]
a
```

Note that only the last SELECT has a useful WHERE statement and returns a result.

**Comment by jonathanstowe** [comment]
It looks like the simplest fix for this would be to make a `ast-value` candidate for `Enumeration` which calls `ast-value` with the `.value` of the `Enumeration` rather than making a whole bunch of new operator candidates.

I'll take a quick look.

**Comment by jonathanstowe** [comment]
> the simplest fix for this would be to make a `ast-value` candidate

Okay not quite as simple as that after all.

**Comment by jonathanstowe** [comment]
Okay, operator candidates it is.

**Comment by jonathanstowe** [comment]
Yeah, operator candidates work.  I'm guessing that there are already more specific candidates in core for the `Enumeration` case which are selected over the less specific ones implemented by `Red`.

BTW `===` is not defined by Red so you'll always get the core version which will always return `False` for a column LHS, so actually that one is right.

**Comment by jonathanstowe** [comment]
And also, in teh `M.^all.grep(*.my-e ⊂ (a))` case you will be getting the single value `a` not a `Positional`, (this is raku's behaviour,) to force a single item list you need to have a trailing comma: `M.^all.grep(*.my-e ⊂ (a,))` or use a `List` instead: `M.^all.grep(*.my-e ⊂ [a])`.

**Comment by jonathanstowe** [comment]
There.

**Comment by FCO** [comment]
I've being also trying to do that, and I plan to throw a X::NYI on ===...

**Comment by FCO** [comment]
Does that work now?

**Comment by patrickbkr** [comment]
Trying the snippet in the OP I now get
```
SQL : BEGIN
BIND: []
SQL : CREATE TABLE "m" (
   id integer NOT NULL primary key AUTOINCREMENT,
   my_e integer NOT NULL 
)
BIND: []
SQL : COMMIT
BIND: []
SQL : BEGIN
BIND: []
SQL : INSERT INTO "m"(
   my_e
)
VALUES(
   ?
)
BIND: [E::a]
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   _rowid_ = last_insert_rowid()
LIMIT 1
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   "m".id = 1
LIMIT 1
BIND: []
SQL : COMMIT
BIND: []
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   "m".my_e = ?
BIND: [E::a]                       <-------------------------- *.my-e == a
a
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   0
BIND: []                       <-------------------------- *.my-e === a
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   0
BIND: []                      <--------------------------  *.my-e ⊂ (a)
SQL : SELECT
   "m".id , "m".my_e as "my-e"
FROM
   "m"
WHERE
   "m".my_e IN ( ?, ? )
BIND: [E::a, E::b]           <--------------------------  *.my-e ⊂ (a, b)
a
```

From above can be seen:
- `==` now works.
- `===` does not work, but according to jonathanstowes comment that's expected, as `=== is not defined by Red so you'll always get the core version`.
- `⊂ (a)` does not work, but that's also expected, since `(a)` is not a list. `(a,)` and `[a]` both would work.
- `⊂ (a, b)` still works, just as before.

So I'm fine with closing this now.

**Comment by FCO** [comment]
Thank you very much you 2
