### ISSUE TITLE
make ^create of multiple items atomic

### ISSUE THREAD

**Issue by FCO** [FCO/Red#505]
> ```raku
> Upload.^create: :misalignments[{ name => 'foo' }];
> ```

On reflection, I'm wondering whether this form should create an _implicit_ transaction under the hood as I think the expectation would be that a single statement should be _atomic_ as far as the caller is concerned and  what actually happens (that the parent row is inserted and the rows for the relation are inserted individually,) is an implementation detail.

I'll have a think how best to address this and probably spawn a new issue to cover it.

__Originally posted by @jonathanstowe in https://github.com/FCO/Red/issues/503#issuecomment-907587134__

**Comment by jonathanstowe** [comment]
Right in my actual code I'm getting:

```
WARNING:  there is no transaction in progress
```

for every row in the "child relation" that is added.  Let me try and replicate in something I can share.
