### ISSUE TITLE
Weirdness with a parameterized role

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#517]
I've just made `JSON::Class` into a parameterized role in order to support `opt-in`  which is all good, but when applied to a Red model like:

```raku
use Red;
use JSON::Class;


my $*RED-DB = database "SQLite";
my $*RED-DEBUG = True;

model Foo does JSON::Class[:opt-in] {
    has Int $.id is serial;
	has Str $.a is column is json;
}

Foo.^create-table;
```

Results in : 

```===SORRY!=== Error while compiling /home/jonathan/devel/raku/3rdparty-modules/Red/js
No such method 'attributes' for invocant of type
'Perl6::Metamodel::CurriedRoleHOW'
at /home/jonathan/devel/raku/3rdparty-modules/Red/js:8
```

It does work fine without the parameter.

And just so we're clear it isn't _just_ `JSON::Class` this gets the same result:

```
use Red;


my $*RED-DB = database "SQLite";
my $*RED-DEBUG = True;

role Bar[Bool :$opt-in = False] {

}

model Foo does Bar[:opt-in] {
    has Int $.id is serial;
	has Str $.a is column;
}

Foo.^create-table;
```

I think it's because the `compose` of the model may need to do something earlier if it gets a CurriedRoleHOW.

**Comment by FCO** [comment]
It seems to pass the tests (only fails on generating the docs). Tomorrow I’ll write sim tests to it and if everything is working, commit it
