### ISSUE TITLE
"syntax error at end of input" when deleting from a postgres table

### ISSUE THREAD

**Issue by whatnext** [FCO/Red#525]
This is happening with

Table.^delete

and returns the following error message $*RED-DEBUG = True

SQL : DELETE FROM table
WHERE 
BIND: []
    Unknown Error!!!
    Please, copy this backtrace and open an issue on https://github.com/FCO/Red/issues/new
    Driver: Red::Driver::Pg
    Original error: DB::Pg::Error::FatalError.new(message => "syntax error at end of input", message-detail => Str, message-hint => Str, context => Str, type => Str, type-localized => "ERROR", state => "42601", statement-position => "31", internal-position => Str, internal-query => Str, schema => Str, table => Str, column => Str, datatype => Str, constraint => Str, source-file => "scan.l", source-line => "998", source-function => "scanner_yyerror")

Original error:
syntax error at end of input
  in method error-check at /opt/rakudo-pkg/share/perl6/site/sources/4C8757DA175EA7235C0CB8A6AD8D207BD9E0699E (DB::Pg::Database) line 123
  in method prepare at /opt/rakudo-pkg/share/perl6/site/sources/4C8757DA175EA7235C0CB8A6AD8D207BD9E0699E (DB::Pg::Database) line 168
  in method stt-exec at /opt/rakudo-pkg/share/perl6/site/sources/C4CCE10064D50A3E67CB3E422A00CBDCCA0174B9 (Red::Driver::Pg) line 88
  in method execute at /opt/rakudo-pkg/share/perl6/site/sources/D33CBC4C3F354F502FEDE51C9F9A17424975F8F6 (Red::Driver) line 112
  in method delete at /opt/rakudo-pkg/share/perl6/site/sources/5AC90CB9D44D57E8198A78D3FA167A43A8BD712C (MetamodelX::Red::Model) line 564

**Comment by FCO** [comment]
Thank you! Could you try it again to see if it's fixed, please?

**Comment by whatnext** [comment]
fix seems to work...
