### ISSUE TITLE
Dynamic variable @*UPDATE not found

### ISSUE THREAD

**Issue by patrickbkr** [FCO/Red#538]
The below code causes the following error:
```
Dynamic variable @*UPDATE not found
  in block  at /home/patrick/repos/Red/lib/MetamodelX/Red/Comparate.pm6 (MetamodelX::Red::Comparate) line 26
  in block <unit> at t.raku line 23
```

```
use Red:api<2>;

enum CITestSetStatus < NEW DONE >;
model CITestSet { ... }

model CIPlatformTestSet is rw is table<ciplatform_test_set> {
    has UInt      $.id          is serial;
    has UInt      $!fk-test-set is referencing( *.id, :model(CITestSet) );
    has CITestSet $.test-set    is relationship( *.fk-test-set );
}
model CITestSet is rw is table<citest_set> {
    has UInt              $.id                 is serial;
    has CITestSetStatus   $.status             is column = NEW;
    has CIPlatformTestSet @.platform-test-sets is relationship( *.fk-test-set );
}

red-defaults('SQLite');
schema(CIPlatformTestSet, CITestSet).create;

my $ts1 = CITestSet.^create;
my $pts = CIPlatformTestSet.^create: :$ts1;
my $ts2 = $pts.test-set;
$ts2.status = DONE;
$ts2.^save;
```

**Comment by jonathanstowe** [comment]
FWIW, I think `$ts2.map({ $_.status = DONE})` should work (and produce the expected SQL,)

**Comment by patrickbkr** [comment]
@jonathanstowe Can you elaborate? Do I understand you correctly that `$.test-set` is not a singular object, but a list? How?

**Comment by jonathanstowe** [comment]
Actually no ignore me, I misread teh example code and mis-interpreted the error.

**Comment by FCO** [comment]
It seems to be the same problem as the other issue: `$ts2` is undefined because the wrong names parameter is being used on `.^create` (`:ts1` should be `:test-set`) then it's running the same code path as in

```raku
CITestSet.^all.map({ .status = DONE }).save;
```

But outside a map, so it can't find `@UPDATE` (that's defined inside `.map`). I probably should change that error message. Any suggestion?

**Comment by FCO** [comment]
I think I should throw an exception when a column/relationship is accessed from outside internal Red code... I'll try to see if that's possible...

**Comment by FCO** [comment]
Using the right named argument (and adding `:update` to save (it seems a bug I have to take a look at)) it seems to work:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/99834/146689293-7683c8ed-8714-4f00-8932-3b2f3016d760.png">

**Comment by patrickbkr** [comment]
@FCO Thanks for your investigation!

> ... it's running the same code path as in
> 
> ```raku
> CITestSet.^all.map({ .status = DONE }).save;
> ```
> 
> But outside a map, so it can't find `@UPDATE` (that's defined inside `.map`). I probably should change that error message. Any suggestion?

I'm not sure I understand it entirely. Is it working as designed when it runs `.status = DONE` in `map` context? If yes, how would the code have to look to do a normal attribute access?

The `:update` thing is a workaround and not something I should remember to use when updating existing objects, correct?

**Comment by FCO** [comment]
> The :update thing is a workaround and not something I should remember to use when updating existing objects, correct?

Correct

> Is it working as designed when it runs .status = DONE in map context?

Yes, it's working with `.map(...).save` but that's for a `ResultSeq` update. The problem on that code is that `$ts2` is undefined. Here is the code running using my last PR:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/99834/146836411-6bc01d68-176b-4eb2-b2bd-80b4af23990e.png">

**Comment by patrickbkr** [comment]
@FCO Thanks for clarifying. Now I understand. So the only thing left in this issue is the `:update` thing.

**Comment by FCO** [comment]
the issue about `:update` should be fixed now...
