### ISSUE TITLE
Map Perl 6 types to DB types

### ISSUE THREAD

**Issue by JJ** [FCO/Red#54]
For instance, DateTime is converted to Str when creating the OR map, although there's something like that in databases, far as I remember.

**Comment by FCO** [comment]
Yes, that’s a feature that is needed to decide how to do that... because it must accept custom types and inflates and deflates (https://github.com/FCO/Red/issues/12)

**Comment by FCO** [comment]
Thank you! Ill open a issue for each type that should be mapped (if you wanna help :) )

**Comment by JJ** [comment]
I can always try :-)
