### ISSUE TITLE
Having issues while trying to modularise code

### ISSUE THREAD

**Issue by samebchase** [FCO/Red#543]
I have code something like:

```
model foo is table<foo> {
    has Int $.id is serial;
    has Str $.name is column;
}

sub MAIN() {
    for foo.^all 
    .grep(*.id == 1) -> $my-foo {
        # do something 
    } 
}
```

which is working fine, but when I try to put `foo` into a file containing Models like so:

```
# lib/Models.rakumod

unit module Models;

use Red:api<2>;

model foo is table<foo>  {
    has Int $.id is serial;
    has Str $.name is column;
}
```

```
use lib 'lib';
use Models;

sub MAIN() {
    for foo.^all 
    .grep(*.id == 1) -> $my-foo {
        # do something 
    } 
}
```

I first got `Undeclared routine foo`, so I changed it to

```
# <common code elided> 

model foo is table<foo> is export {
    has Int $.id is serial;
    has Str $.name is column;
}
```

now I get, `Could not find id`.

My question is, how do I move the model definition to its own module, and then import it, and use its attribute in `grep` etc.?

**Comment by jonathanstowe** [comment]
Your first modularised version should _fully qualify_ the model name:

```raku
use Models;
use Red::Operators;

sub MAIN() {
    for Models::foo.^all.grep(*.id == 1) -> $my-foo {
        # do something 
    } 
}
```

Also use the `Red::Operators` - this brings in the special versions of the operators (e.g. `==` ) that know how to deal with `Red` objects.

**Comment by samebchase** [comment]
@jonathanstowe Hmm, one of the first things I tried was to fully qualify the model name. The thing is, if `foo` is the problem, I should get an error with "can't find `foo`", but I'm getting it for the fields _in_ the model like `id`.

**Comment by samebchase** [comment]
Another thing I'm trying is to pull out the DB code from `MAIN` like this:

```
# lib/Models.rakumod

model foo is table<foo> is export {
    has Int $.id is serial;
    has Str $.name is column;
}

sub bar is export {
    for foo.^all.grep(*.id == 1) -> $my-foo {
        # do something 
    } 
}
```

```
use lib 'lib';
use Models;

sub MAIN() {
    bar;
}
```

Even the above is giving me the same error as before.

**Comment by jonathanstowe** [comment]
```raku
use lib 'lib';
use Models;
use Red;

my $*RED-DB = database 'SQLite';

Models::foo.^create-table;

my $*RED-DEBUG = True;

sub MAIN() {
    for Models::foo.^all.grep(*.id == 1) -> $my-foo {
        # do something 
    } 
}
```

Works as expected for me.

**Comment by samebchase** [comment]
@jonathanstowe I'm using PG, and I don't need any tables to be created, just making queries. 

https://github.com/FCO/Red/blob/master/examples/alive/Schema.rakumod#L62 I think I might need that `schema` call?.

**Comment by jonathanstowe** [comment]
Right, then change the `database` with the correct details and remove the `create-table`.  I just used SQLite for convenience but it makes absolutely no difference to the outcome.

What would be perfect would for you to paste the actual message you are getting.

**Comment by samebchase** [comment]
@jonathanstowe Hey thanks so much for the help, turns out, I followed the 'alive' example in the example code, and I've added the extra `:require<Schema>` in the model definition, (`:require<Models>`, in my case), and it seems to be working.

**Comment by jonathanstowe** [comment]
> it's an internal tool at work which is not open source, so I cannot easily paste the code

:rofl:  to be honest some of my previous examples have been in the same situation and they are only barely concealed, on the other hand you'd have to be making software in the same domain to realise :rofl: 

I've been planning on making an article on how I manage `Red` in a moderate sized application, but just never seem to find the time.

**Comment by FCO** [comment]
> I've been planning on making an article on how I manage Red in a moderate sized application

I would love to read that!
