### ISSUE TITLE
Rakuize code and documentation

### ISSUE THREAD

**Issue by tbrowder** [FCO/Red#567]
+ Change all references to 'perl6' to 'Raku'.
+ Rename module files to '*.rakumod'.
+ Rename pure pod6 files to '*.rakudok'.
+ Rename all scripts with '.pl', '.pl6', or '.p6' to '.raku'.

**Comment by tbrowder** [comment]
Red is looking good. I look forward to giving it another spin!

**Comment by FCO** [comment]
This might been done with my last commits. Please reopen if I have forgotten something.
