### ISSUE TITLE
Circular deps in Red::AST::Infixes block install and use

### ISSUE THREAD

**Issue by MattOates** [FCO/Red#65]
===SORRY!===
Circular module loading detected trying to precompile lib/Red/AST/Infixes.pm6
===> Testing [FAIL]: Red:ver<0.0.1>

Currently blocks tests as well as importing Red for use. Tried taking a look at Red::AST::Infixes and tracing by hand the use statements I couldn't work it out.

**Comment by MattOates** [comment]
Looks like it might be Column uses Model which uses Infixes which is the thing importing Column

**Comment by JJ** [comment]
Got the same error with perl6 2018.09:
```
===> Testing: Red:ver<0.0.1>
===SORRY!===
Circular module loading detected trying to precompile /home/jmerelo/Code/forks/perl6/Red/lib/Red/AST/Infixes.pm6
===SORRY!===
Circular module loading detected trying to precompile /home/jmerelo/Code/forks/perl6/Red/lib/Red/AST/Infixes.pm6
===SORRY!===
Circular module loading detected trying to precompile /home/jmerelo/Code/forks/perl6/Red/lib/Red/AST/Infixes.pm6
===> Testing [FAIL]: Red:ver<0.0.1>
Aborting due to test failure: Red:ver<0.0.1> (use --force-test to override)
```

**Comment by FCO** [comment]
Removing Column from Infixes didn't fix that... :(

**Comment by FCO** [comment]
Fixed, thanks!
