### ISSUE TITLE
Provide an alternative to explicit type on relationship

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#70]
Firstly, thanks your work on this.  It is looking good and can only get better.

The current means for creating relations is expressive and Perl6ish so I wouldn't want it to be replaced, however in  cases where one is creating model definitions for a large number of tables or possibly where the model classes are being generated by some other code it might be more convenient to place the model classes in separate files which means the forward declaration of the stub classes isn't easily possible in the way that it is in the single file.

So I'm seeing an alternative form of the ```relationship``` and ```referencing``` traits which allow the name of the referenced model class to specified as a string and the actual type resolved lazily by dynamic type lookup when it is required to populate the relation.

So I'm thinking something similar to:

```perl6
model Post {
    has Int     $.id        is id;
    has Int     $!author-id is referencing( model => 'Person', key => 'id' );
    has Str     $.title     is unique;
    has Str     $.body      is column;
    has           $.author    is relationship({ .author-id }, model => 'Person');
    has Bool    $.deleted   is column is rw = False;
    has Instant $.created   is column = now;
}

model Person {
    has Int  $.id            is id;
    has Str  $.name          is column;
    has       @.posts         is relationship({ .author-id }, model => 'Post');
}
```

I'm sure that the interface could be refined, but I don't think that this would require a large change to the existing code to handle this, if I get a minute I'll try to hack something up to demonstrate.

/J\

**Comment by FCO** [comment]
Hi jnthn!

Thanks for this issue! I think it's a great idea and once implemented we can probably close the #7.
I'll try to implement that, but if you have that time to help me with this I'd be very thankful (I'd love more eyes on my mess).

Thank you very much

**Comment by FCO** [comment]
@jonathanstowe, do you mean something like this? https://github.com/FCO/Red/tree/master/examples/blog2

**Comment by jonathanstowe** [comment]
Hi,
Yep that's about it/  I've got a partial fix here but still have a few places left where it is trying to use the related type at compile time (so specifically in this example trying to use Person before it is defined,) that's related to the ```$attr.ref```` usage in some places.

But all good.

**Comment by jonathanstowe** [comment]
Ah got it.

I think there should be a "proxy callable" returned by  ```Red::Column.references``` where the ```references```  hasn't been passed explicitly which doesn't look up the referenced model until it is actually needed.  That is something like:

```perl6 
class ReferencesProxy does Callable {
    has Str     $.references-model is required;
    has Str     $.references-key   is required;
    has         $.model;
    has Bool    $!tried-model  = False;

    method model( --> Mu:U ) {
        if !$!tried-model {
            my $model = ::($!references-model);
            say $model;
            if !$model && $model ~~ Failure {
                $model = (require ::($!references-model))
            }
            $!model = $model;
            $!tried-model = True;
        }
        $!model;
    }

    method CALL-ME {
        self.model."{ $!references-key }"()
    }
}

method references(--> Callable) is rw {
    &!references //= do {
        if $!references-model && $!references-key {
            ReferencesProxy.new(:$!references-model, :$!references-key);
        }
        else {
            Callable
        }
    }
}

method ref {
    $!ref //= .() with self.references
}
```
I have the tests passing.  I'll just clean it up a bit and make a PR later :-)

**Comment by FCO** [comment]
Thanks very much! I prefer your implementation than mine. But there are 1 thing on mine that I liked, the option of require a module to use a model with another name (https://github.com/FCO/Red/blob/master/lib/Red/Traits.pm6#L45). What do you think of adding that to your solution?

**Comment by jonathanstowe** [comment]
Yep.  There is also certainly a situation where someone has defined multiple classes in a single compilation unit and the ```require``` may not return the right ```CompUnit``` (which in the one class per file case will be the class type,) so really the  correct thing to do is to attempt the dynamic type lookup of the name requested and then attempt to require either the model name or the requested CompUnit (as per your change,) and then redo the type lookup.

I was being a bit lazy and cargo-culted some of my own code where I knew the class existed in the CompUnit of the same name.

I think that it would be easier to implement the intent of your version by hand rather than attempting to merge it.

**Comment by jonathanstowe** [comment]
In general terms something is causing an otherwise harmless Failure at compile time which can't be compiled.  

Specifically however it is rather difficult to track down, as so much is happening at compile time.  Though I think I have narrowed it down to something in the MetamodelX::Red::Model as a :

```
use Red;
model Foo {
}
```
Fails like that, but simply using Red in a "normal" module doesn't.  But beyond that it may require a lot of divide and conquer debugging.

**Comment by jonathanstowe** [comment]
I'll close this issue now that is implemented and put in a new one to cover the precompilation issue.
