### ISSUE TITLE
Possible problem with the way that exporting is done.

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#76]
Hi,
I get this:

```
[jonathan@coriolanus Red]$ perl6 -Ilib -e 'use Red; use JSON::Marshal'
===SORRY!===
P6opaque: no such attribute '@!dispatchees' on type Routine in a Scalar when trying to get a value
```

```JSON::Marshal`` doesn't have custom export code though it does export some subroutines.

If the two modules are used in the other order there isn't a problem.

**Comment by FCO** [comment]
I forgot to take a look at this... I’ll try it on the released version asap

**Comment by jonathanstowe** [comment]
There are almost certainly other released modules that cause similar and it can be worked around so it's not immediately pressing.

But, just to get your New Year off to an even better start, the : 

```perl6
use JSON::Class;
use Red;


model Foo is table('foo') does JSON::Class {
    has Int $.id    is serial;
    has Str $.name  is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DEBUG-RESPONSE = $_ with %*ENV<RED_DEBUG_RESPONSE>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);


Foo.^create-table;

my $foo = Foo.^create( name => 'Blah');

my $j = $foo.to-json;

say $j;

$j ~~ s/Blah/Woof/;

my $new-foo = Foo.from-json($j);

$new-foo.^save;
```

Works entirely as I hoped it would, I was worried that the various introspections of attributes would interfere with each other:

```
SQL : CREATE TABLE foo(
   name varchar(255) NOT NULL,
   id integer NOT NULL primary key AUTOINCREMENT
)
SQL : INSERT INTO foo(
   name
)
VALUES(
   'Blah'
)
SQL : SELECT
   foo.name , foo.id 
FROM
   foo
WHERE
   _rowid_ = last_insert_rowid()
LIMIT 1
{
  "id": 1,
  "name": "Blah"
}
SQL : UPDATE foo SET
   name = 'Woof',
   id = 1
WHERE id = 1
```

**Comment by jonathanstowe** [comment]
This appears to happen when Red is used before a number of other modules too.  I think it may be related to the declaration of ```module { }``` rather than ```class { }``` that seems to be the common feature of the modules it happens for (and is something I commonly do if I am either only exporting subroutines or defining a number of classes in the same file.)

**Comment by FCO** [comment]
just tested it again and it seems to be working. Closing.
