### ISSUE TITLE
Support for 'in' expressions in generated SQL

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#87]
It would be great if we could have 'IN' expressions, such that, for example, something like:

```perl6
use Red;
  
model Foo {
    has Str $.bar is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Foo.^create-table;

Foo.^all.grep( *.bar ~~ ('abc', 'def')).head;
```

Would generate something like:

```sql
SELECT
   foo.bar 
FROM
   foo
WHERE
   foo.bar in ('abc', 'def')
```

At the moment this causes a type failure.

I guess it's make a candidate for infix ```~~``` that accepts a column and a list and creates some ```Red::AST::In```.  It may at that stage easy to implement one with another ResultSeq on the RHS and generate the sub-query.

This to split up the intent of #21 into bite-size chunks.

**Comment by FCO** [comment]
there's a problem:

```
$ perl6 -e '


multi infix:<~~>(42, 42) { say "aaaaa" }

42 ~~ 42


'
===SORRY!=== Error while compiling -e
Cannot override infix operator '~~', as it is a special form handled directly by the compiler
(consider implementing an ACCEPTS method)
at -e:4
------> multi infix:<~~>⏏(42, 42) { say "aaaaa" }
$ perl6 -e '


class C { method ACCEPTS(42) { note "here"; "ok" } }

say 42 ~~ C


'
here
True
```

**Comment by jonathanstowe** [comment]
So yeah, for classes which are part of Red that isn't a problem as you can make the appropriate ACCEPTS method.  For everything else there would need to be another operator.

**Comment by jonathanstowe** [comment]
Maybe stretch the set operators ⊂ (<)  and ⊃ (>) to this?

**Comment by FCO** [comment]
The ACCEPTS only return a Bool

**Comment by FCO** [comment]
Set operators are good idea.

**Comment by jonathanstowe** [comment]
That's nearly it I'd say.  It may also make all infix expressions with a subselect on the RHS work as a side effect.

**Comment by FCO** [comment]
Rhs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanstowe** [comment]
"Right Hand Side"

**Comment by jonathanstowe** [comment]
What I meant was that:

``perl6
Foo.^rs.grep(*.bar-id eq Bar.^rs.grep( *.name eq 'one' ).map( *.id ).ast);
````

Might work.  It actually doesn't :-( Giving instead:

Ambiguous call to 'infix:<eq>(Red::Column, Red::AST::Select)'; these signatures all match:
:(Red::AST $a, $b)
:($a, Red::AST $b)
  in method grep at /home/jns/me/Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 92
  in block <unit> at rs-rhs line 32
```

But that's not so difficult to fix.

**Comment by jonathanstowe** [comment]
I'll put another issue for generic sub-select handling.  But I think this one is good to go.
