### ISSUE TITLE
Support for union of resultseqs in SQL generation.

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#88]
In the following it would be nice if the union operator ```(|)``` or ```∪``` between two ```ResultSeq``` were to produce a new ```ResultSeq``` with the union of both:

```perl6
use Red;

model Foo {
    has Str $.bar is column;
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Foo.^create-table;

(Foo.^all.grep( *.bar eq 'abc') (|) Foo.^all.grep( *.bar eq 'cde')).head;
```
E.g. would generate:

```sql

SELECT
   foo.bar 
FROM
   foo
WHERE
   foo.bar = 'abc'

UNION

SELECT
   foo.bar 
FROM
   foo
WHERE
   foo.bar = 'cde'

```

This would require a new operator candidate and possibly some small changes to ```ResultSeq``` (possibly a new subclass that was specialized to doing set operations like this.)

Part of the "great actually lay out what #21 requires" .... ;-)

**Comment by FCO** [comment]
Could you test if should be closed, please?

**Comment by jonathanstowe** [comment]
Looks good to me!  Top Work there!
