### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#89]
Currently the SQL generators directly interpolate the values on the RHS of expressions into the SQL statement, this could be a problem for some applications that may accept query values from user input for instance. So it would make sense to use the placeholder facility that most modern DB engines provide.

The change would be quite large but relatively simple in design as I see it: the AST objects will collect the bound values, the translators will gather the values from the AST objects and then pass them to the driver's execute.

It may be prudent to start this before making much more functionality in the SQL generation.

**Comment by FCO** [comment]
Red was built with that in mind. If you take a look here (https://github.com/FCO/Red/blob/master/lib/Red/Operators.pm6) you’ll see that the operator have different candidates for RO and RW values, and generate different ast. If you take a look at the drivers translation methods (eg. https://github.com/FCO/Red/blob/master/lib/Red/Driver/CommonSQL.pm6) you’ll see that it returns always a string (the generated SQL) and an array (that should be a list of values to bind on the query). I think when I rewrote the drivers methods (this is the second time) I was lazy to implement the bindings “extractor”.
All that to agree with you: yes that’s really important!
Thanks!

**Comment by jonathanstowe** [comment]
I hadn't quite got the significance of the ```is rw``` traits on the parameters ;-)  So that's all good then.

I'll leave this here as a reminder to put that back.

**Comment by FCO** [comment]
```
$ perl6 -Ilib -MRed -e '
my $*RED-DB = database "SQLite";
model M is table<mmm> { has Int $.a is column }
M.^create-table;


my $*RED-DEBUG = True;
say M.^all.grep: *.a == 42;

my $a = 42;
say M.^all.grep: *.a == $a;

'
SQL : SELECT
   mmm.a 
FROM
   mmm
WHERE
   mmm.a = 42
BIND: []
()
SQL : SELECT
   mmm.a 
FROM
   mmm
WHERE
   mmm.a = ?
BIND: [42]
()
```

**Comment by jonathanstowe** [comment]
You beauty. I'll test when I get home 💋

**Comment by FCO** [comment]
I just implemented that for infixes... the travel is coming and I’m having less and less time... :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanstowe** [comment]
That looks great.  Sorry I didn't get back sooner.  I was rather overtaken by events.   This looks great.

Good to close IMO. :+1:
