### ISSUE TITLE
Allow creation of Red::Driver::* from an existing DB object

### ISSUE THREAD

**Issue by jonathanstowe** [FCO/Red#94]
It would be useful if the ```database``` helper and the ```Red::Driver``` constructor could take an already created and connected  ```DBDish::Connection``` or ```DB::Pg```  (for instance,) rather than creating on for itself.

This would allow the developer to use features of the DB that wouldn't be naturally exposed in the Red or possible share the handle with other modules.

My primary use case at the moment is to be able to use the ```listen``` method from ```DB::Pg``` in an application and it doesn't seem particularly natural to expose these in ```Red``` as no other DB has this interface.

**Comment by jonathanstowe** [comment]
Well I have:

```perl6
use DB::Pg;
use Red;
need Red::Driver::Pg;

my $p = DB::Pg.new(conninfo => 'host=127.0.0.1 user=postgres dbname=xtdc1_blank');

my $r = $p.query("select * from return_status");
for $r.hashes -> %h {
    say %h.perl;
}

$r.finish;


model ReturnStatus is table('return_status') {
    has Int $.id        is serial;
    has Str $.status    is column;
    has Int $.sequence_number is column;
}

my $*RED-DB = Red::Driver::Pg.new(dbh => $p);


for ReturnStatus.^all -> $rs {
    say $rs;
}
```

Working, which I'll PR in a bit, but there's something weird going on when I try to use use  ```database```

**Comment by FCO** [comment]
I think that makes sense... but about listen and notify, I was wondering that could be possible to create a Supply/Supplier interface for that... I’m not sure yet how...

**Comment by FCO** [comment]
Sorry, I think I answered on the wrong place...
